-d C:\Users\rui\Desktop\iphone_screen\gowin_fpga_mipi_prj\recv_corsslink_data\recv_corsslink_data\impl\gwsynthesis\recv_corsslink_data.vg
-p GW1NR-9C-LQFP144P-6
-pn GW1NR-LV9LQ144PC6/I5
-cst C:\Users\rui\Desktop\iphone_screen\gowin_fpga_mipi_prj\recv_corsslink_data\recv_corsslink_data\src\recv_corsslink_data.cst
-cfg C:\Users\rui\Desktop\iphone_screen\gowin_fpga_mipi_prj\recv_corsslink_data\recv_corsslink_data\impl\pnr\device.cfg
-sdc C:\Users\rui\Desktop\iphone_screen\gowin_fpga_mipi_prj\recv_corsslink_data\recv_corsslink_data\src\recv_corsslink_data.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
