/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.14.0.75.2 */
/* Module Version: 5.8 */
/* C:/lscc/diamond/3.14/ispfpga/bin/nt64/scuba -w -bus_exp 7 -bb -arch sn5w00 -type ebfifo -width 32 -depth 512 -rwidth 32 -regout -no_enable -reset_rel async -pe 1 -pf 511 -n pmi_fifo_dcELar151105125125123232104c3636 -pmi -lang verilog  */
/* Tue Jul 22 00:50:15 2025 */


`timescale 1 ns / 1 ps
module pmi_fifo_dcELar151105125125123232104c3636 (Data, WrClock, RdClock, 
    WrEn, RdEn, Reset, RPReset, Q, Empty, Full, AlmostEmpty, AlmostFull)/* synthesis NGD_DRC_MASK=1 */;
    input wire [31:0] Data;
    input wire WrClock;
    input wire RdClock;
    input wire WrEn;
    input wire RdEn;
    input wire Reset;
    input wire RPReset;
    output wire [31:0] Q;
    output wire Empty;
    output wire Full;
    output wire AlmostEmpty;
    output wire AlmostFull;

    wire invout_1;
    wire invout_0;
    wire w_g2b_xor_cluster_1;
    wire r_g2b_xor_cluster_1;
    wire w_gdata_0;
    wire w_gdata_1;
    wire w_gdata_2;
    wire w_gdata_3;
    wire w_gdata_4;
    wire w_gdata_5;
    wire w_gdata_6;
    wire w_gdata_7;
    wire w_gdata_8;
    wire wptr_0;
    wire wptr_1;
    wire wptr_2;
    wire wptr_3;
    wire wptr_4;
    wire wptr_5;
    wire wptr_6;
    wire wptr_7;
    wire wptr_8;
    wire wptr_9;
    wire r_gdata_0;
    wire r_gdata_1;
    wire r_gdata_2;
    wire r_gdata_3;
    wire r_gdata_4;
    wire r_gdata_5;
    wire r_gdata_6;
    wire r_gdata_7;
    wire r_gdata_8;
    wire rptr_0;
    wire rptr_1;
    wire rptr_2;
    wire rptr_3;
    wire rptr_4;
    wire rptr_5;
    wire rptr_6;
    wire rptr_7;
    wire rptr_8;
    wire rptr_9;
    wire w_gcount_0;
    wire w_gcount_1;
    wire w_gcount_2;
    wire w_gcount_3;
    wire w_gcount_4;
    wire w_gcount_5;
    wire w_gcount_6;
    wire w_gcount_7;
    wire w_gcount_8;
    wire w_gcount_9;
    wire r_gcount_0;
    wire r_gcount_1;
    wire r_gcount_2;
    wire r_gcount_3;
    wire r_gcount_4;
    wire r_gcount_5;
    wire r_gcount_6;
    wire r_gcount_7;
    wire r_gcount_8;
    wire r_gcount_9;
    wire w_gcount_r20;
    wire w_gcount_r0;
    wire w_gcount_r21;
    wire w_gcount_r1;
    wire w_gcount_r22;
    wire w_gcount_r2;
    wire w_gcount_r23;
    wire w_gcount_r3;
    wire w_gcount_r24;
    wire w_gcount_r4;
    wire w_gcount_r25;
    wire w_gcount_r5;
    wire w_gcount_r26;
    wire w_gcount_r6;
    wire w_gcount_r27;
    wire w_gcount_r7;
    wire w_gcount_r28;
    wire w_gcount_r8;
    wire w_gcount_r29;
    wire w_gcount_r9;
    wire r_gcount_w20;
    wire r_gcount_w0;
    wire r_gcount_w21;
    wire r_gcount_w1;
    wire r_gcount_w22;
    wire r_gcount_w2;
    wire r_gcount_w23;
    wire r_gcount_w3;
    wire r_gcount_w24;
    wire r_gcount_w4;
    wire r_gcount_w25;
    wire r_gcount_w5;
    wire r_gcount_w26;
    wire r_gcount_w6;
    wire r_gcount_w27;
    wire r_gcount_w7;
    wire r_gcount_w28;
    wire r_gcount_w8;
    wire r_gcount_w29;
    wire r_gcount_w9;
    wire empty_i;
    wire full_i;
    wire rRst;
    wire iwcount_0;
    wire iwcount_1;
    wire w_gctr_ci;
    wire iwcount_2;
    wire iwcount_3;
    wire co0;
    wire iwcount_4;
    wire iwcount_5;
    wire co1;
    wire iwcount_6;
    wire iwcount_7;
    wire co2;
    wire iwcount_8;
    wire iwcount_9;
    wire co4;
    wire co3;
    wire wcount_9;
    wire ircount_0;
    wire ircount_1;
    wire r_gctr_ci;
    wire ircount_2;
    wire ircount_3;
    wire co0_1;
    wire ircount_4;
    wire ircount_5;
    wire co1_1;
    wire ircount_6;
    wire ircount_7;
    wire co2_1;
    wire ircount_8;
    wire ircount_9;
    wire co4_1;
    wire co3_1;
    wire rcount_9;
    wire cmp_ci;
    wire rcount_0;
    wire rcount_1;
    wire co0_2;
    wire rcount_2;
    wire rcount_3;
    wire co1_2;
    wire rcount_4;
    wire rcount_5;
    wire co2_2;
    wire rcount_6;
    wire rcount_7;
    wire co3_2;
    wire empty_cmp_clr;
    wire rcount_8;
    wire empty_cmp_set;
    wire empty_d;
    wire empty_d_c;
    wire cmp_ci_1;
    wire wcount_0;
    wire wcount_1;
    wire co0_3;
    wire wcount_2;
    wire wcount_3;
    wire co1_3;
    wire wcount_4;
    wire wcount_5;
    wire co2_3;
    wire wcount_6;
    wire wcount_7;
    wire co3_3;
    wire full_cmp_clr;
    wire wcount_8;
    wire full_cmp_set;
    wire full_d;
    wire full_d_c;
    wire iae_setcount_0;
    wire iae_setcount_1;
    wire ae_set_ctr_ci;
    wire iae_setcount_2;
    wire iae_setcount_3;
    wire co0_4;
    wire iae_setcount_4;
    wire iae_setcount_5;
    wire co1_4;
    wire iae_setcount_6;
    wire iae_setcount_7;
    wire co2_4;
    wire iae_setcount_8;
    wire iae_setcount_9;
    wire co4_2;
    wire co3_4;
    wire ae_setcount_9;
    wire rden_i;
    wire cmp_ci_2;
    wire wcount_r0;
    wire wcount_r1;
    wire ae_setcount_0;
    wire ae_setcount_1;
    wire co0_5;
    wire wcount_r2;
    wire wcount_r3;
    wire ae_setcount_2;
    wire ae_setcount_3;
    wire co1_5;
    wire wcount_r4;
    wire wcount_r5;
    wire ae_setcount_4;
    wire ae_setcount_5;
    wire co2_5;
    wire w_g2b_xor_cluster_0;
    wire wcount_r7;
    wire ae_setcount_6;
    wire ae_setcount_7;
    wire co3_5;
    wire wcount_r8;
    wire ae_set_cmp_clr;
    wire ae_setcount_8;
    wire ae_set_cmp_set;
    wire ae_set_d;
    wire ae_set_d_c;
    wire iaf_setcount_0;
    wire iaf_setcount_1;
    wire af_set_ctr_ci;
    wire iaf_setcount_2;
    wire iaf_setcount_3;
    wire co0_6;
    wire iaf_setcount_4;
    wire iaf_setcount_5;
    wire co1_6;
    wire iaf_setcount_6;
    wire iaf_setcount_7;
    wire co2_6;
    wire iaf_setcount_8;
    wire iaf_setcount_9;
    wire co4_3;
    wire co3_6;
    wire af_setcount_9;
    wire wren_i;
    wire cmp_ci_3;
    wire rcount_w0;
    wire rcount_w1;
    wire af_setcount_0;
    wire af_setcount_1;
    wire co0_7;
    wire rcount_w2;
    wire rcount_w3;
    wire af_setcount_2;
    wire af_setcount_3;
    wire co1_7;
    wire rcount_w4;
    wire rcount_w5;
    wire af_setcount_4;
    wire af_setcount_5;
    wire co2_7;
    wire r_g2b_xor_cluster_0;
    wire rcount_w7;
    wire af_setcount_6;
    wire af_setcount_7;
    wire co3_7;
    wire rcount_w8;
    wire af_set_cmp_clr;
    wire af_setcount_8;
    wire af_set_cmp_set;
    wire af_set;
    wire scuba_vhi;
    wire scuba_vlo;
    wire af_set_c;

    AND2 AND2_t20 (.A(WrEn), .B(invout_1), .Z(wren_i));

    INV INV_1 (.A(full_i), .Z(invout_1));

    AND2 AND2_t19 (.A(RdEn), .B(invout_0), .Z(rden_i));

    INV INV_0 (.A(empty_i), .Z(invout_0));

    OR2 OR2_t18 (.A(Reset), .B(RPReset), .Z(rRst));

    XOR2 XOR2_t17 (.A(wcount_0), .B(wcount_1), .Z(w_gdata_0));

    XOR2 XOR2_t16 (.A(wcount_1), .B(wcount_2), .Z(w_gdata_1));

    XOR2 XOR2_t15 (.A(wcount_2), .B(wcount_3), .Z(w_gdata_2));

    XOR2 XOR2_t14 (.A(wcount_3), .B(wcount_4), .Z(w_gdata_3));

    XOR2 XOR2_t13 (.A(wcount_4), .B(wcount_5), .Z(w_gdata_4));

    XOR2 XOR2_t12 (.A(wcount_5), .B(wcount_6), .Z(w_gdata_5));

    XOR2 XOR2_t11 (.A(wcount_6), .B(wcount_7), .Z(w_gdata_6));

    XOR2 XOR2_t10 (.A(wcount_7), .B(wcount_8), .Z(w_gdata_7));

    XOR2 XOR2_t9 (.A(wcount_8), .B(wcount_9), .Z(w_gdata_8));

    XOR2 XOR2_t8 (.A(rcount_0), .B(rcount_1), .Z(r_gdata_0));

    XOR2 XOR2_t7 (.A(rcount_1), .B(rcount_2), .Z(r_gdata_1));

    XOR2 XOR2_t6 (.A(rcount_2), .B(rcount_3), .Z(r_gdata_2));

    XOR2 XOR2_t5 (.A(rcount_3), .B(rcount_4), .Z(r_gdata_3));

    XOR2 XOR2_t4 (.A(rcount_4), .B(rcount_5), .Z(r_gdata_4));

    XOR2 XOR2_t3 (.A(rcount_5), .B(rcount_6), .Z(r_gdata_5));

    XOR2 XOR2_t2 (.A(rcount_6), .B(rcount_7), .Z(r_gdata_6));

    XOR2 XOR2_t1 (.A(rcount_7), .B(rcount_8), .Z(r_gdata_7));

    XOR2 XOR2_t0 (.A(rcount_8), .B(rcount_9), .Z(r_gdata_8));

    defparam LUT4_27.initval =  16'h6996 ;
    ROM16X1A LUT4_27 (.AD3(w_gcount_r26), .AD2(w_gcount_r27), .AD1(w_gcount_r28), 
        .AD0(w_gcount_r29), .DO0(w_g2b_xor_cluster_0));

    defparam LUT4_26.initval =  16'h6996 ;
    ROM16X1A LUT4_26 (.AD3(w_gcount_r22), .AD2(w_gcount_r23), .AD1(w_gcount_r24), 
        .AD0(w_gcount_r25), .DO0(w_g2b_xor_cluster_1));

    defparam LUT4_25.initval =  16'h6996 ;
    ROM16X1A LUT4_25 (.AD3(w_gcount_r28), .AD2(w_gcount_r29), .AD1(scuba_vlo), 
        .AD0(scuba_vlo), .DO0(wcount_r8));

    defparam LUT4_24.initval =  16'h6996 ;
    ROM16X1A LUT4_24 (.AD3(w_gcount_r27), .AD2(w_gcount_r28), .AD1(w_gcount_r29), 
        .AD0(scuba_vlo), .DO0(wcount_r7));

    defparam LUT4_23.initval =  16'h6996 ;
    ROM16X1A LUT4_23 (.AD3(w_gcount_r25), .AD2(w_gcount_r26), .AD1(w_gcount_r27), 
        .AD0(wcount_r8), .DO0(wcount_r5));

    defparam LUT4_22.initval =  16'h6996 ;
    ROM16X1A LUT4_22 (.AD3(w_gcount_r24), .AD2(w_gcount_r25), .AD1(w_gcount_r26), 
        .AD0(wcount_r7), .DO0(wcount_r4));

    defparam LUT4_21.initval =  16'h6996 ;
    ROM16X1A LUT4_21 (.AD3(w_gcount_r23), .AD2(w_gcount_r24), .AD1(w_gcount_r25), 
        .AD0(w_g2b_xor_cluster_0), .DO0(wcount_r3));

    defparam LUT4_20.initval =  16'h6996 ;
    ROM16X1A LUT4_20 (.AD3(w_g2b_xor_cluster_0), .AD2(w_g2b_xor_cluster_1), 
        .AD1(scuba_vlo), .AD0(scuba_vlo), .DO0(wcount_r2));

    defparam LUT4_19.initval =  16'h6996 ;
    ROM16X1A LUT4_19 (.AD3(w_g2b_xor_cluster_0), .AD2(w_g2b_xor_cluster_1), 
        .AD1(w_gcount_r21), .AD0(scuba_vlo), .DO0(wcount_r1));

    defparam LUT4_18.initval =  16'h6996 ;
    ROM16X1A LUT4_18 (.AD3(w_g2b_xor_cluster_0), .AD2(w_g2b_xor_cluster_1), 
        .AD1(w_gcount_r20), .AD0(w_gcount_r21), .DO0(wcount_r0));

    defparam LUT4_17.initval =  16'h6996 ;
    ROM16X1A LUT4_17 (.AD3(r_gcount_w26), .AD2(r_gcount_w27), .AD1(r_gcount_w28), 
        .AD0(r_gcount_w29), .DO0(r_g2b_xor_cluster_0));

    defparam LUT4_16.initval =  16'h6996 ;
    ROM16X1A LUT4_16 (.AD3(r_gcount_w22), .AD2(r_gcount_w23), .AD1(r_gcount_w24), 
        .AD0(r_gcount_w25), .DO0(r_g2b_xor_cluster_1));

    defparam LUT4_15.initval =  16'h6996 ;
    ROM16X1A LUT4_15 (.AD3(r_gcount_w28), .AD2(r_gcount_w29), .AD1(scuba_vlo), 
        .AD0(scuba_vlo), .DO0(rcount_w8));

    defparam LUT4_14.initval =  16'h6996 ;
    ROM16X1A LUT4_14 (.AD3(r_gcount_w27), .AD2(r_gcount_w28), .AD1(r_gcount_w29), 
        .AD0(scuba_vlo), .DO0(rcount_w7));

    defparam LUT4_13.initval =  16'h6996 ;
    ROM16X1A LUT4_13 (.AD3(r_gcount_w25), .AD2(r_gcount_w26), .AD1(r_gcount_w27), 
        .AD0(rcount_w8), .DO0(rcount_w5));

    defparam LUT4_12.initval =  16'h6996 ;
    ROM16X1A LUT4_12 (.AD3(r_gcount_w24), .AD2(r_gcount_w25), .AD1(r_gcount_w26), 
        .AD0(rcount_w7), .DO0(rcount_w4));

    defparam LUT4_11.initval =  16'h6996 ;
    ROM16X1A LUT4_11 (.AD3(r_gcount_w23), .AD2(r_gcount_w24), .AD1(r_gcount_w25), 
        .AD0(r_g2b_xor_cluster_0), .DO0(rcount_w3));

    defparam LUT4_10.initval =  16'h6996 ;
    ROM16X1A LUT4_10 (.AD3(r_g2b_xor_cluster_0), .AD2(r_g2b_xor_cluster_1), 
        .AD1(scuba_vlo), .AD0(scuba_vlo), .DO0(rcount_w2));

    defparam LUT4_9.initval =  16'h6996 ;
    ROM16X1A LUT4_9 (.AD3(r_g2b_xor_cluster_0), .AD2(r_g2b_xor_cluster_1), 
        .AD1(r_gcount_w21), .AD0(scuba_vlo), .DO0(rcount_w1));

    defparam LUT4_8.initval =  16'h6996 ;
    ROM16X1A LUT4_8 (.AD3(r_g2b_xor_cluster_0), .AD2(r_g2b_xor_cluster_1), 
        .AD1(r_gcount_w20), .AD0(r_gcount_w21), .DO0(rcount_w0));

    defparam LUT4_7.initval =  16'h0410 ;
    ROM16X1A LUT4_7 (.AD3(rptr_9), .AD2(rcount_9), .AD1(w_gcount_r29), .AD0(scuba_vlo), 
        .DO0(empty_cmp_set));

    defparam LUT4_6.initval =  16'h1004 ;
    ROM16X1A LUT4_6 (.AD3(rptr_9), .AD2(rcount_9), .AD1(w_gcount_r29), .AD0(scuba_vlo), 
        .DO0(empty_cmp_clr));

    defparam LUT4_5.initval =  16'h0140 ;
    ROM16X1A LUT4_5 (.AD3(wptr_9), .AD2(wcount_9), .AD1(r_gcount_w29), .AD0(scuba_vlo), 
        .DO0(full_cmp_set));

    defparam LUT4_4.initval =  16'h4001 ;
    ROM16X1A LUT4_4 (.AD3(wptr_9), .AD2(wcount_9), .AD1(r_gcount_w29), .AD0(scuba_vlo), 
        .DO0(full_cmp_clr));

    defparam LUT4_3.initval =  16'h13c8 ;
    ROM16X1A LUT4_3 (.AD3(ae_setcount_9), .AD2(rcount_9), .AD1(w_gcount_r29), 
        .AD0(rptr_9), .DO0(ae_set_cmp_set));

    defparam LUT4_2.initval =  16'h2004 ;
    ROM16X1A LUT4_2 (.AD3(ae_setcount_9), .AD2(rcount_9), .AD1(w_gcount_r29), 
        .AD0(rptr_9), .DO0(ae_set_cmp_clr));

    defparam LUT4_1.initval =  16'h4c32 ;
    ROM16X1A LUT4_1 (.AD3(af_setcount_9), .AD2(wcount_9), .AD1(r_gcount_w29), 
        .AD0(wptr_9), .DO0(af_set_cmp_set));

    defparam LUT4_0.initval =  16'h8001 ;
    ROM16X1A LUT4_0 (.AD3(af_setcount_9), .AD2(wcount_9), .AD1(r_gcount_w29), 
        .AD0(wptr_9), .DO0(af_set_cmp_clr));

    defparam pdp_ram_0_0_1.INIT_DATA = "STATIC" ;
    defparam pdp_ram_0_0_1.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam pdp_ram_0_0_1.CSDECODE_R = "0b001" ;
    defparam pdp_ram_0_0_1.CSDECODE_W = "0b001" ;
    defparam pdp_ram_0_0_1.GSR = "ENABLED" ;
    defparam pdp_ram_0_0_1.RESETMODE = "ASYNC" ;
    defparam pdp_ram_0_0_1.REGMODE = "OUTREG" ;
    defparam pdp_ram_0_0_1.DATA_WIDTH_R = 18 ;
    defparam pdp_ram_0_0_1.DATA_WIDTH_W = 18 ;
    PDPW8KE pdp_ram_0_0_1 (.DI17(Data[17]), .DI16(Data[16]), .DI15(Data[15]), 
        .DI14(Data[14]), .DI13(Data[13]), .DI12(Data[12]), .DI11(Data[11]), 
        .DI10(Data[10]), .DI9(Data[9]), .DI8(Data[8]), .DI7(Data[7]), .DI6(Data[6]), 
        .DI5(Data[5]), .DI4(Data[4]), .DI3(Data[3]), .DI2(Data[2]), .DI1(Data[1]), 
        .DI0(Data[0]), .ADW8(wptr_8), .ADW7(wptr_7), .ADW6(wptr_6), .ADW5(wptr_5), 
        .ADW4(wptr_4), .ADW3(wptr_3), .ADW2(wptr_2), .ADW1(wptr_1), .ADW0(wptr_0), 
        .BE1(scuba_vhi), .BE0(scuba_vhi), .CEW(wren_i), .CLKW(WrClock), 
        .CSW2(scuba_vlo), .CSW1(scuba_vlo), .CSW0(scuba_vhi), .ADR12(rptr_8), 
        .ADR11(rptr_7), .ADR10(rptr_6), .ADR9(rptr_5), .ADR8(rptr_4), .ADR7(rptr_3), 
        .ADR6(rptr_2), .ADR5(rptr_1), .ADR4(rptr_0), .ADR3(scuba_vlo), .ADR2(scuba_vlo), 
        .ADR1(scuba_vlo), .ADR0(scuba_vlo), .CER(scuba_vhi), .OCER(scuba_vhi), 
        .CLKR(RdClock), .CSR2(scuba_vlo), .CSR1(scuba_vlo), .CSR0(rden_i), 
        .RST(Reset), .DO17(Q[8]), .DO16(Q[7]), .DO15(Q[6]), .DO14(Q[5]), 
        .DO13(Q[4]), .DO12(Q[3]), .DO11(Q[2]), .DO10(Q[1]), .DO9(Q[0]), 
        .DO8(Q[17]), .DO7(Q[16]), .DO6(Q[15]), .DO5(Q[14]), .DO4(Q[13]), 
        .DO3(Q[12]), .DO2(Q[11]), .DO1(Q[10]), .DO0(Q[9]))
             /* synthesis MEM_LPC_FILE="pmi_fifo_dcELar151105125125123232104c3636__PMIX__512__32__32__-1A" */
             /* synthesis MEM_INIT_FILE="" */;

    defparam pdp_ram_0_1_0.INIT_DATA = "STATIC" ;
    defparam pdp_ram_0_1_0.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam pdp_ram_0_1_0.CSDECODE_R = "0b001" ;
    defparam pdp_ram_0_1_0.CSDECODE_W = "0b001" ;
    defparam pdp_ram_0_1_0.GSR = "ENABLED" ;
    defparam pdp_ram_0_1_0.RESETMODE = "ASYNC" ;
    defparam pdp_ram_0_1_0.REGMODE = "OUTREG" ;
    defparam pdp_ram_0_1_0.DATA_WIDTH_R = 18 ;
    defparam pdp_ram_0_1_0.DATA_WIDTH_W = 18 ;
    PDPW8KE pdp_ram_0_1_0 (.DI17(scuba_vlo), .DI16(scuba_vlo), .DI15(scuba_vlo), 
        .DI14(scuba_vlo), .DI13(Data[31]), .DI12(Data[30]), .DI11(Data[29]), 
        .DI10(Data[28]), .DI9(Data[27]), .DI8(Data[26]), .DI7(Data[25]), 
        .DI6(Data[24]), .DI5(Data[23]), .DI4(Data[22]), .DI3(Data[21]), 
        .DI2(Data[20]), .DI1(Data[19]), .DI0(Data[18]), .ADW8(wptr_8), .ADW7(wptr_7), 
        .ADW6(wptr_6), .ADW5(wptr_5), .ADW4(wptr_4), .ADW3(wptr_3), .ADW2(wptr_2), 
        .ADW1(wptr_1), .ADW0(wptr_0), .BE1(scuba_vhi), .BE0(scuba_vhi), 
        .CEW(wren_i), .CLKW(WrClock), .CSW2(scuba_vlo), .CSW1(scuba_vlo), 
        .CSW0(scuba_vhi), .ADR12(rptr_8), .ADR11(rptr_7), .ADR10(rptr_6), 
        .ADR9(rptr_5), .ADR8(rptr_4), .ADR7(rptr_3), .ADR6(rptr_2), .ADR5(rptr_1), 
        .ADR4(rptr_0), .ADR3(scuba_vlo), .ADR2(scuba_vlo), .ADR1(scuba_vlo), 
        .ADR0(scuba_vlo), .CER(scuba_vhi), .OCER(scuba_vhi), .CLKR(RdClock), 
        .CSR2(scuba_vlo), .CSR1(scuba_vlo), .CSR0(rden_i), .RST(Reset), 
        .DO17(Q[26]), .DO16(Q[25]), .DO15(Q[24]), .DO14(Q[23]), .DO13(Q[22]), 
        .DO12(Q[21]), .DO11(Q[20]), .DO10(Q[19]), .DO9(Q[18]), .DO8(), .DO7(), 
        .DO6(), .DO5(), .DO4(Q[31]), .DO3(Q[30]), .DO2(Q[29]), .DO1(Q[28]), 
        .DO0(Q[27]))
             /* synthesis MEM_LPC_FILE="pmi_fifo_dcELar151105125125123232104c3636__PMIX__512__32__32__-1A" */
             /* synthesis MEM_INIT_FILE="" */;

    FD1P3BX FF_123 (.D(iwcount_0), .SP(wren_i), .CK(WrClock), .PD(Reset), 
        .Q(wcount_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_122 (.D(iwcount_1), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_121 (.D(iwcount_2), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_120 (.D(iwcount_3), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_119 (.D(iwcount_4), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_118 (.D(iwcount_5), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_117 (.D(iwcount_6), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_116 (.D(iwcount_7), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_115 (.D(iwcount_8), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_114 (.D(iwcount_9), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_9))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_113 (.D(w_gdata_0), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_112 (.D(w_gdata_1), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_111 (.D(w_gdata_2), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_110 (.D(w_gdata_3), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_109 (.D(w_gdata_4), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_108 (.D(w_gdata_5), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_107 (.D(w_gdata_6), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_106 (.D(w_gdata_7), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_105 (.D(w_gdata_8), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_104 (.D(wcount_9), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_9))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_103 (.D(wcount_0), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_102 (.D(wcount_1), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_101 (.D(wcount_2), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_100 (.D(wcount_3), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_99 (.D(wcount_4), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_98 (.D(wcount_5), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_97 (.D(wcount_6), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_96 (.D(wcount_7), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_95 (.D(wcount_8), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_94 (.D(wcount_9), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_9))
             /* synthesis GSR="ENABLED" */;

    FD1P3BX FF_93 (.D(ircount_0), .SP(rden_i), .CK(RdClock), .PD(rRst), 
        .Q(rcount_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_92 (.D(ircount_1), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_91 (.D(ircount_2), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_90 (.D(ircount_3), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_89 (.D(ircount_4), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_88 (.D(ircount_5), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_87 (.D(ircount_6), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_86 (.D(ircount_7), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_85 (.D(ircount_8), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_84 (.D(ircount_9), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_9))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_83 (.D(r_gdata_0), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_82 (.D(r_gdata_1), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_81 (.D(r_gdata_2), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_80 (.D(r_gdata_3), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_79 (.D(r_gdata_4), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_78 (.D(r_gdata_5), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_77 (.D(r_gdata_6), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_76 (.D(r_gdata_7), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_75 (.D(r_gdata_8), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_74 (.D(rcount_9), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(r_gcount_9))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_73 (.D(rcount_0), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_72 (.D(rcount_1), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_71 (.D(rcount_2), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_70 (.D(rcount_3), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_69 (.D(rcount_4), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_68 (.D(rcount_5), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_67 (.D(rcount_6), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_66 (.D(rcount_7), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_65 (.D(rcount_8), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_64 (.D(rcount_9), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_9))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_63 (.D(w_gcount_0), .CK(RdClock), .CD(Reset), .Q(w_gcount_r0))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_62 (.D(w_gcount_1), .CK(RdClock), .CD(Reset), .Q(w_gcount_r1))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_61 (.D(w_gcount_2), .CK(RdClock), .CD(Reset), .Q(w_gcount_r2))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_60 (.D(w_gcount_3), .CK(RdClock), .CD(Reset), .Q(w_gcount_r3))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_59 (.D(w_gcount_4), .CK(RdClock), .CD(Reset), .Q(w_gcount_r4))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_58 (.D(w_gcount_5), .CK(RdClock), .CD(Reset), .Q(w_gcount_r5))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_57 (.D(w_gcount_6), .CK(RdClock), .CD(Reset), .Q(w_gcount_r6))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_56 (.D(w_gcount_7), .CK(RdClock), .CD(Reset), .Q(w_gcount_r7))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_55 (.D(w_gcount_8), .CK(RdClock), .CD(Reset), .Q(w_gcount_r8))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_54 (.D(w_gcount_9), .CK(RdClock), .CD(Reset), .Q(w_gcount_r9))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_53 (.D(r_gcount_0), .CK(WrClock), .CD(rRst), .Q(r_gcount_w0))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_52 (.D(r_gcount_1), .CK(WrClock), .CD(rRst), .Q(r_gcount_w1))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_51 (.D(r_gcount_2), .CK(WrClock), .CD(rRst), .Q(r_gcount_w2))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_50 (.D(r_gcount_3), .CK(WrClock), .CD(rRst), .Q(r_gcount_w3))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_49 (.D(r_gcount_4), .CK(WrClock), .CD(rRst), .Q(r_gcount_w4))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_48 (.D(r_gcount_5), .CK(WrClock), .CD(rRst), .Q(r_gcount_w5))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_47 (.D(r_gcount_6), .CK(WrClock), .CD(rRst), .Q(r_gcount_w6))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_46 (.D(r_gcount_7), .CK(WrClock), .CD(rRst), .Q(r_gcount_w7))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_45 (.D(r_gcount_8), .CK(WrClock), .CD(rRst), .Q(r_gcount_w8))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_44 (.D(r_gcount_9), .CK(WrClock), .CD(rRst), .Q(r_gcount_w9))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_43 (.D(w_gcount_r0), .CK(RdClock), .CD(Reset), .Q(w_gcount_r20))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_42 (.D(w_gcount_r1), .CK(RdClock), .CD(Reset), .Q(w_gcount_r21))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_41 (.D(w_gcount_r2), .CK(RdClock), .CD(Reset), .Q(w_gcount_r22))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_40 (.D(w_gcount_r3), .CK(RdClock), .CD(Reset), .Q(w_gcount_r23))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_39 (.D(w_gcount_r4), .CK(RdClock), .CD(Reset), .Q(w_gcount_r24))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_38 (.D(w_gcount_r5), .CK(RdClock), .CD(Reset), .Q(w_gcount_r25))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_37 (.D(w_gcount_r6), .CK(RdClock), .CD(Reset), .Q(w_gcount_r26))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_36 (.D(w_gcount_r7), .CK(RdClock), .CD(Reset), .Q(w_gcount_r27))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_35 (.D(w_gcount_r8), .CK(RdClock), .CD(Reset), .Q(w_gcount_r28))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_34 (.D(w_gcount_r9), .CK(RdClock), .CD(Reset), .Q(w_gcount_r29))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_33 (.D(r_gcount_w0), .CK(WrClock), .CD(rRst), .Q(r_gcount_w20))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_32 (.D(r_gcount_w1), .CK(WrClock), .CD(rRst), .Q(r_gcount_w21))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_31 (.D(r_gcount_w2), .CK(WrClock), .CD(rRst), .Q(r_gcount_w22))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_30 (.D(r_gcount_w3), .CK(WrClock), .CD(rRst), .Q(r_gcount_w23))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_29 (.D(r_gcount_w4), .CK(WrClock), .CD(rRst), .Q(r_gcount_w24))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_28 (.D(r_gcount_w5), .CK(WrClock), .CD(rRst), .Q(r_gcount_w25))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_27 (.D(r_gcount_w6), .CK(WrClock), .CD(rRst), .Q(r_gcount_w26))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_26 (.D(r_gcount_w7), .CK(WrClock), .CD(rRst), .Q(r_gcount_w27))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_25 (.D(r_gcount_w8), .CK(WrClock), .CD(rRst), .Q(r_gcount_w28))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_24 (.D(r_gcount_w9), .CK(WrClock), .CD(rRst), .Q(r_gcount_w29))
             /* synthesis GSR="ENABLED" */;

    FD1S3BX FF_23 (.D(empty_d), .CK(RdClock), .PD(rRst), .Q(empty_i))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_22 (.D(full_d), .CK(WrClock), .CD(Reset), .Q(full_i))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_21 (.D(iae_setcount_0), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(ae_setcount_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3BX FF_20 (.D(iae_setcount_1), .SP(rden_i), .CK(RdClock), .PD(rRst), 
        .Q(ae_setcount_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_19 (.D(iae_setcount_2), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(ae_setcount_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_18 (.D(iae_setcount_3), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(ae_setcount_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_17 (.D(iae_setcount_4), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(ae_setcount_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_16 (.D(iae_setcount_5), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(ae_setcount_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_15 (.D(iae_setcount_6), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(ae_setcount_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_14 (.D(iae_setcount_7), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(ae_setcount_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_13 (.D(iae_setcount_8), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(ae_setcount_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_12 (.D(iae_setcount_9), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(ae_setcount_9))
             /* synthesis GSR="ENABLED" */;

    FD1S3BX FF_11 (.D(ae_set_d), .CK(RdClock), .PD(rRst), .Q(AlmostEmpty))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_10 (.D(iaf_setcount_0), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(af_setcount_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3BX FF_9 (.D(iaf_setcount_1), .SP(wren_i), .CK(WrClock), .PD(Reset), 
        .Q(af_setcount_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_8 (.D(iaf_setcount_2), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(af_setcount_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_7 (.D(iaf_setcount_3), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(af_setcount_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_6 (.D(iaf_setcount_4), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(af_setcount_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_5 (.D(iaf_setcount_5), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(af_setcount_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_4 (.D(iaf_setcount_6), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(af_setcount_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_3 (.D(iaf_setcount_7), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(af_setcount_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_2 (.D(iaf_setcount_8), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(af_setcount_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_1 (.D(iaf_setcount_9), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(af_setcount_9))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_0 (.D(af_set), .CK(WrClock), .CD(Reset), .Q(AlmostFull))
             /* synthesis GSR="ENABLED" */;

    defparam w_gctr_cia.INJECT1_1 = "NO" ;
    defparam w_gctr_cia.INJECT1_0 = "NO" ;
    defparam w_gctr_cia.INIT1 =  16'h66AA ;
    defparam w_gctr_cia.INIT0 =  16'h66AA ;
    CCU2C w_gctr_cia (.A0(scuba_vlo), .A1(scuba_vhi), .B0(scuba_vlo), .B1(scuba_vhi), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(), .S0(), .S1(), .COUT(w_gctr_ci));

    defparam w_gctr_0.INJECT1_1 = "NO" ;
    defparam w_gctr_0.INJECT1_0 = "NO" ;
    defparam w_gctr_0.INIT1 =  16'h66AA ;
    defparam w_gctr_0.INIT0 =  16'h66AA ;
    CCU2C w_gctr_0 (.A0(wcount_0), .A1(wcount_1), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(w_gctr_ci), .S0(iwcount_0), .S1(iwcount_1), .COUT(co0));

    defparam w_gctr_1.INJECT1_1 = "NO" ;
    defparam w_gctr_1.INJECT1_0 = "NO" ;
    defparam w_gctr_1.INIT1 =  16'h66AA ;
    defparam w_gctr_1.INIT0 =  16'h66AA ;
    CCU2C w_gctr_1 (.A0(wcount_2), .A1(wcount_3), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co0), .S0(iwcount_2), .S1(iwcount_3), .COUT(co1));

    defparam w_gctr_2.INJECT1_1 = "NO" ;
    defparam w_gctr_2.INJECT1_0 = "NO" ;
    defparam w_gctr_2.INIT1 =  16'h66AA ;
    defparam w_gctr_2.INIT0 =  16'h66AA ;
    CCU2C w_gctr_2 (.A0(wcount_4), .A1(wcount_5), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co1), .S0(iwcount_4), .S1(iwcount_5), .COUT(co2));

    defparam w_gctr_3.INJECT1_1 = "NO" ;
    defparam w_gctr_3.INJECT1_0 = "NO" ;
    defparam w_gctr_3.INIT1 =  16'h66AA ;
    defparam w_gctr_3.INIT0 =  16'h66AA ;
    CCU2C w_gctr_3 (.A0(wcount_6), .A1(wcount_7), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co2), .S0(iwcount_6), .S1(iwcount_7), .COUT(co3));

    defparam w_gctr_4.INJECT1_1 = "NO" ;
    defparam w_gctr_4.INJECT1_0 = "NO" ;
    defparam w_gctr_4.INIT1 =  16'h66AA ;
    defparam w_gctr_4.INIT0 =  16'h66AA ;
    CCU2C w_gctr_4 (.A0(wcount_8), .A1(wcount_9), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co3), .S0(iwcount_8), .S1(iwcount_9), .COUT(co4));

    defparam r_gctr_cia.INJECT1_1 = "NO" ;
    defparam r_gctr_cia.INJECT1_0 = "NO" ;
    defparam r_gctr_cia.INIT1 =  16'h66AA ;
    defparam r_gctr_cia.INIT0 =  16'h66AA ;
    CCU2C r_gctr_cia (.A0(scuba_vlo), .A1(scuba_vhi), .B0(scuba_vlo), .B1(scuba_vhi), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(), .S0(), .S1(), .COUT(r_gctr_ci));

    defparam r_gctr_0.INJECT1_1 = "NO" ;
    defparam r_gctr_0.INJECT1_0 = "NO" ;
    defparam r_gctr_0.INIT1 =  16'h66AA ;
    defparam r_gctr_0.INIT0 =  16'h66AA ;
    CCU2C r_gctr_0 (.A0(rcount_0), .A1(rcount_1), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(r_gctr_ci), .S0(ircount_0), .S1(ircount_1), .COUT(co0_1));

    defparam r_gctr_1.INJECT1_1 = "NO" ;
    defparam r_gctr_1.INJECT1_0 = "NO" ;
    defparam r_gctr_1.INIT1 =  16'h66AA ;
    defparam r_gctr_1.INIT0 =  16'h66AA ;
    CCU2C r_gctr_1 (.A0(rcount_2), .A1(rcount_3), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co0_1), .S0(ircount_2), .S1(ircount_3), .COUT(co1_1));

    defparam r_gctr_2.INJECT1_1 = "NO" ;
    defparam r_gctr_2.INJECT1_0 = "NO" ;
    defparam r_gctr_2.INIT1 =  16'h66AA ;
    defparam r_gctr_2.INIT0 =  16'h66AA ;
    CCU2C r_gctr_2 (.A0(rcount_4), .A1(rcount_5), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co1_1), .S0(ircount_4), .S1(ircount_5), .COUT(co2_1));

    defparam r_gctr_3.INJECT1_1 = "NO" ;
    defparam r_gctr_3.INJECT1_0 = "NO" ;
    defparam r_gctr_3.INIT1 =  16'h66AA ;
    defparam r_gctr_3.INIT0 =  16'h66AA ;
    CCU2C r_gctr_3 (.A0(rcount_6), .A1(rcount_7), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co2_1), .S0(ircount_6), .S1(ircount_7), .COUT(co3_1));

    defparam r_gctr_4.INJECT1_1 = "NO" ;
    defparam r_gctr_4.INJECT1_0 = "NO" ;
    defparam r_gctr_4.INIT1 =  16'h66AA ;
    defparam r_gctr_4.INIT0 =  16'h66AA ;
    CCU2C r_gctr_4 (.A0(rcount_8), .A1(rcount_9), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co3_1), .S0(ircount_8), .S1(ircount_9), .COUT(co4_1));

    defparam empty_cmp_ci_a.INJECT1_1 = "NO" ;
    defparam empty_cmp_ci_a.INJECT1_0 = "NO" ;
    defparam empty_cmp_ci_a.INIT1 =  16'h66AA ;
    defparam empty_cmp_ci_a.INIT0 =  16'h66AA ;
    CCU2C empty_cmp_ci_a (.A0(scuba_vlo), .A1(rden_i), .B0(scuba_vlo), .B1(rden_i), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(), .S0(), .S1(), .COUT(cmp_ci));

    defparam empty_cmp_0.INJECT1_1 = "NO" ;
    defparam empty_cmp_0.INJECT1_0 = "NO" ;
    defparam empty_cmp_0.INIT1 =  16'h99AA ;
    defparam empty_cmp_0.INIT0 =  16'h99AA ;
    CCU2C empty_cmp_0 (.A0(rcount_0), .A1(rcount_1), .B0(wcount_r0), .B1(wcount_r1), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(cmp_ci), .S0(), .S1(), .COUT(co0_2));

    defparam empty_cmp_1.INJECT1_1 = "NO" ;
    defparam empty_cmp_1.INJECT1_0 = "NO" ;
    defparam empty_cmp_1.INIT1 =  16'h99AA ;
    defparam empty_cmp_1.INIT0 =  16'h99AA ;
    CCU2C empty_cmp_1 (.A0(rcount_2), .A1(rcount_3), .B0(wcount_r2), .B1(wcount_r3), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co0_2), .S0(), .S1(), .COUT(co1_2));

    defparam empty_cmp_2.INJECT1_1 = "NO" ;
    defparam empty_cmp_2.INJECT1_0 = "NO" ;
    defparam empty_cmp_2.INIT1 =  16'h99AA ;
    defparam empty_cmp_2.INIT0 =  16'h99AA ;
    CCU2C empty_cmp_2 (.A0(rcount_4), .A1(rcount_5), .B0(wcount_r4), .B1(wcount_r5), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co1_2), .S0(), .S1(), .COUT(co2_2));

    defparam empty_cmp_3.INJECT1_1 = "NO" ;
    defparam empty_cmp_3.INJECT1_0 = "NO" ;
    defparam empty_cmp_3.INIT1 =  16'h99AA ;
    defparam empty_cmp_3.INIT0 =  16'h99AA ;
    CCU2C empty_cmp_3 (.A0(rcount_6), .A1(rcount_7), .B0(w_g2b_xor_cluster_0), 
        .B1(wcount_r7), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co2_2), .S0(), .S1(), .COUT(co3_2));

    defparam empty_cmp_4.INJECT1_1 = "NO" ;
    defparam empty_cmp_4.INJECT1_0 = "NO" ;
    defparam empty_cmp_4.INIT1 =  16'h99AA ;
    defparam empty_cmp_4.INIT0 =  16'h99AA ;
    CCU2C empty_cmp_4 (.A0(rcount_8), .A1(empty_cmp_set), .B0(wcount_r8), 
        .B1(empty_cmp_clr), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co3_2), .S0(), .S1(), .COUT(empty_d_c));

    defparam a0.INJECT1_1 = "NO" ;
    defparam a0.INJECT1_0 = "NO" ;
    defparam a0.INIT1 =  16'h66AA ;
    defparam a0.INIT0 =  16'h66AA ;
    CCU2C a0 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(empty_d_c), .S0(empty_d), .S1(), .COUT());

    defparam full_cmp_ci_a.INJECT1_1 = "NO" ;
    defparam full_cmp_ci_a.INJECT1_0 = "NO" ;
    defparam full_cmp_ci_a.INIT1 =  16'h66AA ;
    defparam full_cmp_ci_a.INIT0 =  16'h66AA ;
    CCU2C full_cmp_ci_a (.A0(scuba_vlo), .A1(wren_i), .B0(scuba_vlo), .B1(wren_i), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(), .S0(), .S1(), .COUT(cmp_ci_1));

    defparam full_cmp_0.INJECT1_1 = "NO" ;
    defparam full_cmp_0.INJECT1_0 = "NO" ;
    defparam full_cmp_0.INIT1 =  16'h99AA ;
    defparam full_cmp_0.INIT0 =  16'h99AA ;
    CCU2C full_cmp_0 (.A0(wcount_0), .A1(wcount_1), .B0(rcount_w0), .B1(rcount_w1), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(cmp_ci_1), .S0(), .S1(), .COUT(co0_3));

    defparam full_cmp_1.INJECT1_1 = "NO" ;
    defparam full_cmp_1.INJECT1_0 = "NO" ;
    defparam full_cmp_1.INIT1 =  16'h99AA ;
    defparam full_cmp_1.INIT0 =  16'h99AA ;
    CCU2C full_cmp_1 (.A0(wcount_2), .A1(wcount_3), .B0(rcount_w2), .B1(rcount_w3), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co0_3), .S0(), .S1(), .COUT(co1_3));

    defparam full_cmp_2.INJECT1_1 = "NO" ;
    defparam full_cmp_2.INJECT1_0 = "NO" ;
    defparam full_cmp_2.INIT1 =  16'h99AA ;
    defparam full_cmp_2.INIT0 =  16'h99AA ;
    CCU2C full_cmp_2 (.A0(wcount_4), .A1(wcount_5), .B0(rcount_w4), .B1(rcount_w5), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co1_3), .S0(), .S1(), .COUT(co2_3));

    defparam full_cmp_3.INJECT1_1 = "NO" ;
    defparam full_cmp_3.INJECT1_0 = "NO" ;
    defparam full_cmp_3.INIT1 =  16'h99AA ;
    defparam full_cmp_3.INIT0 =  16'h99AA ;
    CCU2C full_cmp_3 (.A0(wcount_6), .A1(wcount_7), .B0(r_g2b_xor_cluster_0), 
        .B1(rcount_w7), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co2_3), .S0(), .S1(), .COUT(co3_3));

    defparam full_cmp_4.INJECT1_1 = "NO" ;
    defparam full_cmp_4.INJECT1_0 = "NO" ;
    defparam full_cmp_4.INIT1 =  16'h99AA ;
    defparam full_cmp_4.INIT0 =  16'h99AA ;
    CCU2C full_cmp_4 (.A0(wcount_8), .A1(full_cmp_set), .B0(rcount_w8), 
        .B1(full_cmp_clr), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co3_3), .S0(), .S1(), .COUT(full_d_c));

    defparam a1.INJECT1_1 = "NO" ;
    defparam a1.INJECT1_0 = "NO" ;
    defparam a1.INIT1 =  16'h66AA ;
    defparam a1.INIT0 =  16'h66AA ;
    CCU2C a1 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(full_d_c), .S0(full_d), .S1(), .COUT());

    defparam ae_set_ctr_cia.INJECT1_1 = "NO" ;
    defparam ae_set_ctr_cia.INJECT1_0 = "NO" ;
    defparam ae_set_ctr_cia.INIT1 =  16'h66AA ;
    defparam ae_set_ctr_cia.INIT0 =  16'h66AA ;
    CCU2C ae_set_ctr_cia (.A0(scuba_vlo), .A1(scuba_vhi), .B0(scuba_vlo), 
        .B1(scuba_vhi), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(), .S0(), .S1(), .COUT(ae_set_ctr_ci));

    defparam ae_set_ctr_0.INJECT1_1 = "NO" ;
    defparam ae_set_ctr_0.INJECT1_0 = "NO" ;
    defparam ae_set_ctr_0.INIT1 =  16'h66AA ;
    defparam ae_set_ctr_0.INIT0 =  16'h66AA ;
    CCU2C ae_set_ctr_0 (.A0(ae_setcount_0), .A1(ae_setcount_1), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(ae_set_ctr_ci), .S0(iae_setcount_0), .S1(iae_setcount_1), 
        .COUT(co0_4));

    defparam ae_set_ctr_1.INJECT1_1 = "NO" ;
    defparam ae_set_ctr_1.INJECT1_0 = "NO" ;
    defparam ae_set_ctr_1.INIT1 =  16'h66AA ;
    defparam ae_set_ctr_1.INIT0 =  16'h66AA ;
    CCU2C ae_set_ctr_1 (.A0(ae_setcount_2), .A1(ae_setcount_3), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co0_4), .S0(iae_setcount_2), .S1(iae_setcount_3), 
        .COUT(co1_4));

    defparam ae_set_ctr_2.INJECT1_1 = "NO" ;
    defparam ae_set_ctr_2.INJECT1_0 = "NO" ;
    defparam ae_set_ctr_2.INIT1 =  16'h66AA ;
    defparam ae_set_ctr_2.INIT0 =  16'h66AA ;
    CCU2C ae_set_ctr_2 (.A0(ae_setcount_4), .A1(ae_setcount_5), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co1_4), .S0(iae_setcount_4), .S1(iae_setcount_5), 
        .COUT(co2_4));

    defparam ae_set_ctr_3.INJECT1_1 = "NO" ;
    defparam ae_set_ctr_3.INJECT1_0 = "NO" ;
    defparam ae_set_ctr_3.INIT1 =  16'h66AA ;
    defparam ae_set_ctr_3.INIT0 =  16'h66AA ;
    CCU2C ae_set_ctr_3 (.A0(ae_setcount_6), .A1(ae_setcount_7), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co2_4), .S0(iae_setcount_6), .S1(iae_setcount_7), 
        .COUT(co3_4));

    defparam ae_set_ctr_4.INJECT1_1 = "NO" ;
    defparam ae_set_ctr_4.INJECT1_0 = "NO" ;
    defparam ae_set_ctr_4.INIT1 =  16'h66AA ;
    defparam ae_set_ctr_4.INIT0 =  16'h66AA ;
    CCU2C ae_set_ctr_4 (.A0(ae_setcount_8), .A1(ae_setcount_9), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co3_4), .S0(iae_setcount_8), .S1(iae_setcount_9), 
        .COUT(co4_2));

    defparam ae_set_cmp_ci_a.INJECT1_1 = "NO" ;
    defparam ae_set_cmp_ci_a.INJECT1_0 = "NO" ;
    defparam ae_set_cmp_ci_a.INIT1 =  16'h66AA ;
    defparam ae_set_cmp_ci_a.INIT0 =  16'h66AA ;
    CCU2C ae_set_cmp_ci_a (.A0(scuba_vlo), .A1(rden_i), .B0(scuba_vlo), 
        .B1(rden_i), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(), .S0(), .S1(), .COUT(cmp_ci_2));

    defparam ae_set_cmp_0.INJECT1_1 = "NO" ;
    defparam ae_set_cmp_0.INJECT1_0 = "NO" ;
    defparam ae_set_cmp_0.INIT1 =  16'h99AA ;
    defparam ae_set_cmp_0.INIT0 =  16'h99AA ;
    CCU2C ae_set_cmp_0 (.A0(ae_setcount_0), .A1(ae_setcount_1), .B0(wcount_r0), 
        .B1(wcount_r1), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(cmp_ci_2), .S0(), .S1(), .COUT(co0_5));

    defparam ae_set_cmp_1.INJECT1_1 = "NO" ;
    defparam ae_set_cmp_1.INJECT1_0 = "NO" ;
    defparam ae_set_cmp_1.INIT1 =  16'h99AA ;
    defparam ae_set_cmp_1.INIT0 =  16'h99AA ;
    CCU2C ae_set_cmp_1 (.A0(ae_setcount_2), .A1(ae_setcount_3), .B0(wcount_r2), 
        .B1(wcount_r3), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co0_5), .S0(), .S1(), .COUT(co1_5));

    defparam ae_set_cmp_2.INJECT1_1 = "NO" ;
    defparam ae_set_cmp_2.INJECT1_0 = "NO" ;
    defparam ae_set_cmp_2.INIT1 =  16'h99AA ;
    defparam ae_set_cmp_2.INIT0 =  16'h99AA ;
    CCU2C ae_set_cmp_2 (.A0(ae_setcount_4), .A1(ae_setcount_5), .B0(wcount_r4), 
        .B1(wcount_r5), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co1_5), .S0(), .S1(), .COUT(co2_5));

    defparam ae_set_cmp_3.INJECT1_1 = "NO" ;
    defparam ae_set_cmp_3.INJECT1_0 = "NO" ;
    defparam ae_set_cmp_3.INIT1 =  16'h99AA ;
    defparam ae_set_cmp_3.INIT0 =  16'h99AA ;
    CCU2C ae_set_cmp_3 (.A0(ae_setcount_6), .A1(ae_setcount_7), .B0(w_g2b_xor_cluster_0), 
        .B1(wcount_r7), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co2_5), .S0(), .S1(), .COUT(co3_5));

    defparam ae_set_cmp_4.INJECT1_1 = "NO" ;
    defparam ae_set_cmp_4.INJECT1_0 = "NO" ;
    defparam ae_set_cmp_4.INIT1 =  16'h99AA ;
    defparam ae_set_cmp_4.INIT0 =  16'h99AA ;
    CCU2C ae_set_cmp_4 (.A0(ae_setcount_8), .A1(ae_set_cmp_set), .B0(wcount_r8), 
        .B1(ae_set_cmp_clr), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co3_5), .S0(), .S1(), .COUT(ae_set_d_c));

    defparam a2.INJECT1_1 = "NO" ;
    defparam a2.INJECT1_0 = "NO" ;
    defparam a2.INIT1 =  16'h66AA ;
    defparam a2.INIT0 =  16'h66AA ;
    CCU2C a2 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(ae_set_d_c), .S0(ae_set_d), .S1(), .COUT());

    defparam af_set_ctr_cia.INJECT1_1 = "NO" ;
    defparam af_set_ctr_cia.INJECT1_0 = "NO" ;
    defparam af_set_ctr_cia.INIT1 =  16'h66AA ;
    defparam af_set_ctr_cia.INIT0 =  16'h66AA ;
    CCU2C af_set_ctr_cia (.A0(scuba_vlo), .A1(scuba_vhi), .B0(scuba_vlo), 
        .B1(scuba_vhi), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(), .S0(), .S1(), .COUT(af_set_ctr_ci));

    defparam af_set_ctr_0.INJECT1_1 = "NO" ;
    defparam af_set_ctr_0.INJECT1_0 = "NO" ;
    defparam af_set_ctr_0.INIT1 =  16'h66AA ;
    defparam af_set_ctr_0.INIT0 =  16'h66AA ;
    CCU2C af_set_ctr_0 (.A0(af_setcount_0), .A1(af_setcount_1), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(af_set_ctr_ci), .S0(iaf_setcount_0), .S1(iaf_setcount_1), 
        .COUT(co0_6));

    defparam af_set_ctr_1.INJECT1_1 = "NO" ;
    defparam af_set_ctr_1.INJECT1_0 = "NO" ;
    defparam af_set_ctr_1.INIT1 =  16'h66AA ;
    defparam af_set_ctr_1.INIT0 =  16'h66AA ;
    CCU2C af_set_ctr_1 (.A0(af_setcount_2), .A1(af_setcount_3), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co0_6), .S0(iaf_setcount_2), .S1(iaf_setcount_3), 
        .COUT(co1_6));

    defparam af_set_ctr_2.INJECT1_1 = "NO" ;
    defparam af_set_ctr_2.INJECT1_0 = "NO" ;
    defparam af_set_ctr_2.INIT1 =  16'h66AA ;
    defparam af_set_ctr_2.INIT0 =  16'h66AA ;
    CCU2C af_set_ctr_2 (.A0(af_setcount_4), .A1(af_setcount_5), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co1_6), .S0(iaf_setcount_4), .S1(iaf_setcount_5), 
        .COUT(co2_6));

    defparam af_set_ctr_3.INJECT1_1 = "NO" ;
    defparam af_set_ctr_3.INJECT1_0 = "NO" ;
    defparam af_set_ctr_3.INIT1 =  16'h66AA ;
    defparam af_set_ctr_3.INIT0 =  16'h66AA ;
    CCU2C af_set_ctr_3 (.A0(af_setcount_6), .A1(af_setcount_7), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co2_6), .S0(iaf_setcount_6), .S1(iaf_setcount_7), 
        .COUT(co3_6));

    defparam af_set_ctr_4.INJECT1_1 = "NO" ;
    defparam af_set_ctr_4.INJECT1_0 = "NO" ;
    defparam af_set_ctr_4.INIT1 =  16'h66AA ;
    defparam af_set_ctr_4.INIT0 =  16'h66AA ;
    CCU2C af_set_ctr_4 (.A0(af_setcount_8), .A1(af_setcount_9), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co3_6), .S0(iaf_setcount_8), .S1(iaf_setcount_9), 
        .COUT(co4_3));

    defparam af_set_cmp_ci_a.INJECT1_1 = "NO" ;
    defparam af_set_cmp_ci_a.INJECT1_0 = "NO" ;
    defparam af_set_cmp_ci_a.INIT1 =  16'h66AA ;
    defparam af_set_cmp_ci_a.INIT0 =  16'h66AA ;
    CCU2C af_set_cmp_ci_a (.A0(scuba_vlo), .A1(wren_i), .B0(scuba_vlo), 
        .B1(wren_i), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(), .S0(), .S1(), .COUT(cmp_ci_3));

    defparam af_set_cmp_0.INJECT1_1 = "NO" ;
    defparam af_set_cmp_0.INJECT1_0 = "NO" ;
    defparam af_set_cmp_0.INIT1 =  16'h99AA ;
    defparam af_set_cmp_0.INIT0 =  16'h99AA ;
    CCU2C af_set_cmp_0 (.A0(af_setcount_0), .A1(af_setcount_1), .B0(rcount_w0), 
        .B1(rcount_w1), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(cmp_ci_3), .S0(), .S1(), .COUT(co0_7));

    defparam af_set_cmp_1.INJECT1_1 = "NO" ;
    defparam af_set_cmp_1.INJECT1_0 = "NO" ;
    defparam af_set_cmp_1.INIT1 =  16'h99AA ;
    defparam af_set_cmp_1.INIT0 =  16'h99AA ;
    CCU2C af_set_cmp_1 (.A0(af_setcount_2), .A1(af_setcount_3), .B0(rcount_w2), 
        .B1(rcount_w3), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co0_7), .S0(), .S1(), .COUT(co1_7));

    defparam af_set_cmp_2.INJECT1_1 = "NO" ;
    defparam af_set_cmp_2.INJECT1_0 = "NO" ;
    defparam af_set_cmp_2.INIT1 =  16'h99AA ;
    defparam af_set_cmp_2.INIT0 =  16'h99AA ;
    CCU2C af_set_cmp_2 (.A0(af_setcount_4), .A1(af_setcount_5), .B0(rcount_w4), 
        .B1(rcount_w5), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co1_7), .S0(), .S1(), .COUT(co2_7));

    defparam af_set_cmp_3.INJECT1_1 = "NO" ;
    defparam af_set_cmp_3.INJECT1_0 = "NO" ;
    defparam af_set_cmp_3.INIT1 =  16'h99AA ;
    defparam af_set_cmp_3.INIT0 =  16'h99AA ;
    CCU2C af_set_cmp_3 (.A0(af_setcount_6), .A1(af_setcount_7), .B0(r_g2b_xor_cluster_0), 
        .B1(rcount_w7), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co2_7), .S0(), .S1(), .COUT(co3_7));

    defparam af_set_cmp_4.INJECT1_1 = "NO" ;
    defparam af_set_cmp_4.INJECT1_0 = "NO" ;
    defparam af_set_cmp_4.INIT1 =  16'h99AA ;
    defparam af_set_cmp_4.INIT0 =  16'h99AA ;
    CCU2C af_set_cmp_4 (.A0(af_setcount_8), .A1(af_set_cmp_set), .B0(rcount_w8), 
        .B1(af_set_cmp_clr), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co3_7), .S0(), .S1(), .COUT(af_set_c));

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    defparam a3.INJECT1_1 = "NO" ;
    defparam a3.INJECT1_0 = "NO" ;
    defparam a3.INIT1 =  16'h66AA ;
    defparam a3.INIT0 =  16'h66AA ;
    CCU2C a3 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(af_set_c), .S0(af_set), .S1(), .COUT());

    assign Empty = empty_i;
    assign Full = full_i;


    // exemplar begin
    // exemplar attribute pdp_ram_0_0_1 MEM_LPC_FILE pmi_fifo_dcELar151105125125123232104c3636__PMIX__512__32__32__-1A
    // exemplar attribute pdp_ram_0_0_1 MEM_INIT_FILE 
    // exemplar attribute pdp_ram_0_1_0 MEM_LPC_FILE pmi_fifo_dcELar151105125125123232104c3636__PMIX__512__32__32__-1A
    // exemplar attribute pdp_ram_0_1_0 MEM_INIT_FILE 
    // exemplar attribute FF_123 GSR ENABLED
    // exemplar attribute FF_122 GSR ENABLED
    // exemplar attribute FF_121 GSR ENABLED
    // exemplar attribute FF_120 GSR ENABLED
    // exemplar attribute FF_119 GSR ENABLED
    // exemplar attribute FF_118 GSR ENABLED
    // exemplar attribute FF_117 GSR ENABLED
    // exemplar attribute FF_116 GSR ENABLED
    // exemplar attribute FF_115 GSR ENABLED
    // exemplar attribute FF_114 GSR ENABLED
    // exemplar attribute FF_113 GSR ENABLED
    // exemplar attribute FF_112 GSR ENABLED
    // exemplar attribute FF_111 GSR ENABLED
    // exemplar attribute FF_110 GSR ENABLED
    // exemplar attribute FF_109 GSR ENABLED
    // exemplar attribute FF_108 GSR ENABLED
    // exemplar attribute FF_107 GSR ENABLED
    // exemplar attribute FF_106 GSR ENABLED
    // exemplar attribute FF_105 GSR ENABLED
    // exemplar attribute FF_104 GSR ENABLED
    // exemplar attribute FF_103 GSR ENABLED
    // exemplar attribute FF_102 GSR ENABLED
    // exemplar attribute FF_101 GSR ENABLED
    // exemplar attribute FF_100 GSR ENABLED
    // exemplar attribute FF_99 GSR ENABLED
    // exemplar attribute FF_98 GSR ENABLED
    // exemplar attribute FF_97 GSR ENABLED
    // exemplar attribute FF_96 GSR ENABLED
    // exemplar attribute FF_95 GSR ENABLED
    // exemplar attribute FF_94 GSR ENABLED
    // exemplar attribute FF_93 GSR ENABLED
    // exemplar attribute FF_92 GSR ENABLED
    // exemplar attribute FF_91 GSR ENABLED
    // exemplar attribute FF_90 GSR ENABLED
    // exemplar attribute FF_89 GSR ENABLED
    // exemplar attribute FF_88 GSR ENABLED
    // exemplar attribute FF_87 GSR ENABLED
    // exemplar attribute FF_86 GSR ENABLED
    // exemplar attribute FF_85 GSR ENABLED
    // exemplar attribute FF_84 GSR ENABLED
    // exemplar attribute FF_83 GSR ENABLED
    // exemplar attribute FF_82 GSR ENABLED
    // exemplar attribute FF_81 GSR ENABLED
    // exemplar attribute FF_80 GSR ENABLED
    // exemplar attribute FF_79 GSR ENABLED
    // exemplar attribute FF_78 GSR ENABLED
    // exemplar attribute FF_77 GSR ENABLED
    // exemplar attribute FF_76 GSR ENABLED
    // exemplar attribute FF_75 GSR ENABLED
    // exemplar attribute FF_74 GSR ENABLED
    // exemplar attribute FF_73 GSR ENABLED
    // exemplar attribute FF_72 GSR ENABLED
    // exemplar attribute FF_71 GSR ENABLED
    // exemplar attribute FF_70 GSR ENABLED
    // exemplar attribute FF_69 GSR ENABLED
    // exemplar attribute FF_68 GSR ENABLED
    // exemplar attribute FF_67 GSR ENABLED
    // exemplar attribute FF_66 GSR ENABLED
    // exemplar attribute FF_65 GSR ENABLED
    // exemplar attribute FF_64 GSR ENABLED
    // exemplar attribute FF_63 GSR ENABLED
    // exemplar attribute FF_62 GSR ENABLED
    // exemplar attribute FF_61 GSR ENABLED
    // exemplar attribute FF_60 GSR ENABLED
    // exemplar attribute FF_59 GSR ENABLED
    // exemplar attribute FF_58 GSR ENABLED
    // exemplar attribute FF_57 GSR ENABLED
    // exemplar attribute FF_56 GSR ENABLED
    // exemplar attribute FF_55 GSR ENABLED
    // exemplar attribute FF_54 GSR ENABLED
    // exemplar attribute FF_53 GSR ENABLED
    // exemplar attribute FF_52 GSR ENABLED
    // exemplar attribute FF_51 GSR ENABLED
    // exemplar attribute FF_50 GSR ENABLED
    // exemplar attribute FF_49 GSR ENABLED
    // exemplar attribute FF_48 GSR ENABLED
    // exemplar attribute FF_47 GSR ENABLED
    // exemplar attribute FF_46 GSR ENABLED
    // exemplar attribute FF_45 GSR ENABLED
    // exemplar attribute FF_44 GSR ENABLED
    // exemplar attribute FF_43 GSR ENABLED
    // exemplar attribute FF_42 GSR ENABLED
    // exemplar attribute FF_41 GSR ENABLED
    // exemplar attribute FF_40 GSR ENABLED
    // exemplar attribute FF_39 GSR ENABLED
    // exemplar attribute FF_38 GSR ENABLED
    // exemplar attribute FF_37 GSR ENABLED
    // exemplar attribute FF_36 GSR ENABLED
    // exemplar attribute FF_35 GSR ENABLED
    // exemplar attribute FF_34 GSR ENABLED
    // exemplar attribute FF_33 GSR ENABLED
    // exemplar attribute FF_32 GSR ENABLED
    // exemplar attribute FF_31 GSR ENABLED
    // exemplar attribute FF_30 GSR ENABLED
    // exemplar attribute FF_29 GSR ENABLED
    // exemplar attribute FF_28 GSR ENABLED
    // exemplar attribute FF_27 GSR ENABLED
    // exemplar attribute FF_26 GSR ENABLED
    // exemplar attribute FF_25 GSR ENABLED
    // exemplar attribute FF_24 GSR ENABLED
    // exemplar attribute FF_23 GSR ENABLED
    // exemplar attribute FF_22 GSR ENABLED
    // exemplar attribute FF_21 GSR ENABLED
    // exemplar attribute FF_20 GSR ENABLED
    // exemplar attribute FF_19 GSR ENABLED
    // exemplar attribute FF_18 GSR ENABLED
    // exemplar attribute FF_17 GSR ENABLED
    // exemplar attribute FF_16 GSR ENABLED
    // exemplar attribute FF_15 GSR ENABLED
    // exemplar attribute FF_14 GSR ENABLED
    // exemplar attribute FF_13 GSR ENABLED
    // exemplar attribute FF_12 GSR ENABLED
    // exemplar attribute FF_11 GSR ENABLED
    // exemplar attribute FF_10 GSR ENABLED
    // exemplar attribute FF_9 GSR ENABLED
    // exemplar attribute FF_8 GSR ENABLED
    // exemplar attribute FF_7 GSR ENABLED
    // exemplar attribute FF_6 GSR ENABLED
    // exemplar attribute FF_5 GSR ENABLED
    // exemplar attribute FF_4 GSR ENABLED
    // exemplar attribute FF_3 GSR ENABLED
    // exemplar attribute FF_2 GSR ENABLED
    // exemplar attribute FF_1 GSR ENABLED
    // exemplar attribute FF_0 GSR ENABLED
    // exemplar end

endmodule
/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.14.0.75.2 */
/* Module Version: 5.1 */
/* C:/lscc/diamond/3.14/ispfpga/bin/nt64/scuba -w -bus_exp 7 -bb -arch sn5w00 -pfu_fifo -type ebfifo -sync_mode -depth 4 -width 16 -pf 3 -pe 1 -regout -no_enable -n pmi_fifoLLr1304416b8506c3 -pmi -lang verilog  */
/* Tue Jul 22 00:50:15 2025 */


`timescale 1 ns / 1 ps
module pmi_fifoLLr1304416b8506c3 (Data, Clock, WrEn, RdEn, Reset, Q, 
    Empty, Full, AlmostEmpty, AlmostFull)/* synthesis NGD_DRC_MASK=1 */;
    input wire [15:0] Data;
    input wire Clock;
    input wire WrEn;
    input wire RdEn;
    input wire Reset;
    output wire [15:0] Q;
    output wire Empty;
    output wire Full;
    output wire AlmostEmpty;
    output wire AlmostFull;

    wire invout_2;
    wire invout_1;
    wire rden_i_inv;
    wire invout_0;
    wire cnt_con_inv;
    wire fcnt_en_inv_inv;
    wire fcnt_en;
    wire empty_i;
    wire empty_d;
    wire full_i;
    wire full_d;
    wire edataout0;
    wire edataout1;
    wire edataout2;
    wire edataout3;
    wire edataout4;
    wire edataout5;
    wire edataout6;
    wire edataout7;
    wire edataout8;
    wire edataout9;
    wire edataout10;
    wire edataout11;
    wire edataout12;
    wire edataout13;
    wire edataout14;
    wire edataout15;
    wire ifcount_0;
    wire ifcount_1;
    wire bdcnt_bctr_ci;
    wire ifcount_2;
    wire co1;
    wire cnt_con;
    wire co0;
    wire cmp_ci;
    wire rden_i;
    wire co0_1;
    wire cmp_le_1;
    wire cmp_le_1_c;
    wire cmp_ci_1;
    wire wren_i;
    wire co0_2;
    wire wren_i_inv;
    wire cmp_ge_d1;
    wire cmp_ge_d1_c;
    wire iwcount_0;
    wire iwcount_1;
    wire w_ctr_ci;
    wire iwcount_2;
    wire co1_1;
    wire co0_3;
    wire wcount_2;
    wire ircount_0;
    wire ircount_1;
    wire r_ctr_ci;
    wire ircount_2;
    wire co1_2;
    wire co0_4;
    wire rcount_2;
    wire cmp_ci_2;
    wire co0_5;
    wire ae_d;
    wire ae_d_c;
    wire cmp_ci_3;
    wire fcnt_en_inv;
    wire r_nw_inv;
    wire fcount_0;
    wire fcount_1;
    wire co0_6;
    wire r_nw;
    wire fcount_2;
    wire af_d;
    wire scuba_vlo;
    wire af_d_c;
    wire rdataout15;
    wire rdataout14;
    wire rdataout13;
    wire rdataout12;
    wire rdataout11;
    wire rdataout10;
    wire rdataout9;
    wire rdataout8;
    wire rdataout7;
    wire rdataout6;
    wire rdataout5;
    wire rdataout4;
    wire rdataout3;
    wire rdataout2;
    wire rdataout1;
    wire rdataout0;
    wire rcount_1;
    wire rcount_0;
    wire dec0_wre3;
    wire scuba_vhi;
    wire wcount_1;
    wire wcount_0;

    AND2 AND2_t4 (.A(WrEn), .B(invout_2), .Z(wren_i));

    INV INV_8 (.A(full_i), .Z(invout_2));

    AND2 AND2_t3 (.A(RdEn), .B(invout_1), .Z(rden_i));

    INV INV_7 (.A(empty_i), .Z(invout_1));

    AND2 AND2_t2 (.A(wren_i), .B(rden_i_inv), .Z(cnt_con));

    XOR2 XOR2_t1 (.A(wren_i), .B(rden_i), .Z(fcnt_en));

    INV INV_6 (.A(rden_i), .Z(rden_i_inv));

    INV INV_5 (.A(wren_i), .Z(wren_i_inv));

    defparam LUT4_2.initval =  16'h3232 ;
    ROM16X1A LUT4_2 (.AD3(scuba_vlo), .AD2(cmp_le_1), .AD1(wren_i), .AD0(empty_i), 
        .DO0(empty_d));

    defparam LUT4_1.initval =  16'h3232 ;
    ROM16X1A LUT4_1 (.AD3(scuba_vlo), .AD2(cmp_ge_d1), .AD1(rden_i), .AD0(full_i), 
        .DO0(full_d));

    defparam LUT4_0.initval =  16'h8000 ;
    ROM16X1A LUT4_0 (.AD3(scuba_vhi), .AD2(wren_i), .AD1(scuba_vhi), .AD0(scuba_vhi), 
        .DO0(dec0_wre3));

    AND2 AND2_t0 (.A(rden_i), .B(invout_0), .Z(r_nw));

    INV INV_4 (.A(wren_i), .Z(invout_0));

    INV INV_3 (.A(fcnt_en), .Z(fcnt_en_inv));

    INV INV_2 (.A(cnt_con), .Z(cnt_con_inv));

    INV INV_1 (.A(r_nw), .Z(r_nw_inv));

    INV INV_0 (.A(fcnt_en_inv), .Z(fcnt_en_inv_inv));

    FD1P3DX FF_44 (.D(ifcount_0), .SP(fcnt_en), .CK(Clock), .CD(Reset), 
        .Q(fcount_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_43 (.D(ifcount_1), .SP(fcnt_en), .CK(Clock), .CD(Reset), 
        .Q(fcount_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_42 (.D(ifcount_2), .SP(fcnt_en), .CK(Clock), .CD(Reset), 
        .Q(fcount_2))
             /* synthesis GSR="ENABLED" */;

    FD1S3BX FF_41 (.D(empty_d), .CK(Clock), .PD(Reset), .Q(empty_i))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_40 (.D(full_d), .CK(Clock), .CD(Reset), .Q(full_i))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_39 (.D(iwcount_0), .SP(wren_i), .CK(Clock), .CD(Reset), .Q(wcount_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_38 (.D(iwcount_1), .SP(wren_i), .CK(Clock), .CD(Reset), .Q(wcount_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_37 (.D(iwcount_2), .SP(wren_i), .CK(Clock), .CD(Reset), .Q(wcount_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_36 (.D(ircount_0), .SP(rden_i), .CK(Clock), .CD(Reset), .Q(rcount_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_35 (.D(ircount_1), .SP(rden_i), .CK(Clock), .CD(Reset), .Q(rcount_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_34 (.D(ircount_2), .SP(rden_i), .CK(Clock), .CD(Reset), .Q(rcount_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_33 (.D(edataout0), .SP(scuba_vhi), .CK(Clock), .CD(Reset), 
        .Q(Q[0]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_32 (.D(rdataout0), .SP(rden_i), .CK(Clock), .CD(Reset), .Q(edataout0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_31 (.D(edataout1), .SP(scuba_vhi), .CK(Clock), .CD(Reset), 
        .Q(Q[1]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_30 (.D(rdataout1), .SP(rden_i), .CK(Clock), .CD(Reset), .Q(edataout1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_29 (.D(edataout2), .SP(scuba_vhi), .CK(Clock), .CD(Reset), 
        .Q(Q[2]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_28 (.D(rdataout2), .SP(rden_i), .CK(Clock), .CD(Reset), .Q(edataout2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_27 (.D(edataout3), .SP(scuba_vhi), .CK(Clock), .CD(Reset), 
        .Q(Q[3]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_26 (.D(rdataout3), .SP(rden_i), .CK(Clock), .CD(Reset), .Q(edataout3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_25 (.D(edataout4), .SP(scuba_vhi), .CK(Clock), .CD(Reset), 
        .Q(Q[4]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_24 (.D(rdataout4), .SP(rden_i), .CK(Clock), .CD(Reset), .Q(edataout4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_23 (.D(edataout5), .SP(scuba_vhi), .CK(Clock), .CD(Reset), 
        .Q(Q[5]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_22 (.D(rdataout5), .SP(rden_i), .CK(Clock), .CD(Reset), .Q(edataout5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_21 (.D(edataout6), .SP(scuba_vhi), .CK(Clock), .CD(Reset), 
        .Q(Q[6]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_20 (.D(rdataout6), .SP(rden_i), .CK(Clock), .CD(Reset), .Q(edataout6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_19 (.D(edataout7), .SP(scuba_vhi), .CK(Clock), .CD(Reset), 
        .Q(Q[7]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_18 (.D(rdataout7), .SP(rden_i), .CK(Clock), .CD(Reset), .Q(edataout7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_17 (.D(edataout8), .SP(scuba_vhi), .CK(Clock), .CD(Reset), 
        .Q(Q[8]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_16 (.D(rdataout8), .SP(rden_i), .CK(Clock), .CD(Reset), .Q(edataout8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_15 (.D(edataout9), .SP(scuba_vhi), .CK(Clock), .CD(Reset), 
        .Q(Q[9]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_14 (.D(rdataout9), .SP(rden_i), .CK(Clock), .CD(Reset), .Q(edataout9))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_13 (.D(edataout10), .SP(scuba_vhi), .CK(Clock), .CD(Reset), 
        .Q(Q[10]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_12 (.D(rdataout10), .SP(rden_i), .CK(Clock), .CD(Reset), 
        .Q(edataout10))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_11 (.D(edataout11), .SP(scuba_vhi), .CK(Clock), .CD(Reset), 
        .Q(Q[11]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_10 (.D(rdataout11), .SP(rden_i), .CK(Clock), .CD(Reset), 
        .Q(edataout11))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_9 (.D(edataout12), .SP(scuba_vhi), .CK(Clock), .CD(Reset), 
        .Q(Q[12]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_8 (.D(rdataout12), .SP(rden_i), .CK(Clock), .CD(Reset), .Q(edataout12))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_7 (.D(edataout13), .SP(scuba_vhi), .CK(Clock), .CD(Reset), 
        .Q(Q[13]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_6 (.D(rdataout13), .SP(rden_i), .CK(Clock), .CD(Reset), .Q(edataout13))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_5 (.D(edataout14), .SP(scuba_vhi), .CK(Clock), .CD(Reset), 
        .Q(Q[14]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_4 (.D(rdataout14), .SP(rden_i), .CK(Clock), .CD(Reset), .Q(edataout14))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_3 (.D(edataout15), .SP(scuba_vhi), .CK(Clock), .CD(Reset), 
        .Q(Q[15]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_2 (.D(rdataout15), .SP(rden_i), .CK(Clock), .CD(Reset), .Q(edataout15))
             /* synthesis GSR="ENABLED" */;

    FD1S3BX FF_1 (.D(ae_d), .CK(Clock), .PD(Reset), .Q(AlmostEmpty))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_0 (.D(af_d), .CK(Clock), .CD(Reset), .Q(AlmostFull))
             /* synthesis GSR="ENABLED" */;

    defparam bdcnt_bctr_cia.INJECT1_1 = "NO" ;
    defparam bdcnt_bctr_cia.INJECT1_0 = "NO" ;
    defparam bdcnt_bctr_cia.INIT1 =  16'h66AA ;
    defparam bdcnt_bctr_cia.INIT0 =  16'h66AA ;
    CCU2C bdcnt_bctr_cia (.A0(scuba_vlo), .A1(cnt_con), .B0(scuba_vlo), 
        .B1(cnt_con), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(), .S0(), .S1(), .COUT(bdcnt_bctr_ci));

    defparam bdcnt_bctr_0.INJECT1_1 = "NO" ;
    defparam bdcnt_bctr_0.INJECT1_0 = "NO" ;
    defparam bdcnt_bctr_0.INIT1 =  16'h99AA ;
    defparam bdcnt_bctr_0.INIT0 =  16'h99AA ;
    CCU2C bdcnt_bctr_0 (.A0(fcount_0), .A1(fcount_1), .B0(cnt_con), .B1(cnt_con), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(bdcnt_bctr_ci), .S0(ifcount_0), .S1(ifcount_1), .COUT(co0));

    defparam bdcnt_bctr_1.INJECT1_1 = "NO" ;
    defparam bdcnt_bctr_1.INJECT1_0 = "NO" ;
    defparam bdcnt_bctr_1.INIT1 =  16'h99AA ;
    defparam bdcnt_bctr_1.INIT0 =  16'h99AA ;
    CCU2C bdcnt_bctr_1 (.A0(fcount_2), .A1(scuba_vlo), .B0(cnt_con), .B1(cnt_con), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co0), .S0(ifcount_2), .S1(), .COUT(co1));

    defparam e_cmp_ci_a.INJECT1_1 = "NO" ;
    defparam e_cmp_ci_a.INJECT1_0 = "NO" ;
    defparam e_cmp_ci_a.INIT1 =  16'h66AA ;
    defparam e_cmp_ci_a.INIT0 =  16'h66AA ;
    CCU2C e_cmp_ci_a (.A0(scuba_vhi), .A1(scuba_vhi), .B0(scuba_vhi), .B1(scuba_vhi), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(), .S0(), .S1(), .COUT(cmp_ci));

    defparam e_cmp_0.INJECT1_1 = "NO" ;
    defparam e_cmp_0.INJECT1_0 = "NO" ;
    defparam e_cmp_0.INIT1 =  16'h99AA ;
    defparam e_cmp_0.INIT0 =  16'h99AA ;
    CCU2C e_cmp_0 (.A0(rden_i), .A1(scuba_vlo), .B0(fcount_0), .B1(fcount_1), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(cmp_ci), .S0(), .S1(), .COUT(co0_1));

    defparam e_cmp_1.INJECT1_1 = "NO" ;
    defparam e_cmp_1.INJECT1_0 = "NO" ;
    defparam e_cmp_1.INIT1 =  16'h99AA ;
    defparam e_cmp_1.INIT0 =  16'h99AA ;
    CCU2C e_cmp_1 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(fcount_2), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co0_1), .S0(), .S1(), .COUT(cmp_le_1_c));

    defparam a0.INJECT1_1 = "NO" ;
    defparam a0.INJECT1_0 = "NO" ;
    defparam a0.INIT1 =  16'h66AA ;
    defparam a0.INIT0 =  16'h66AA ;
    CCU2C a0 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(cmp_le_1_c), .S0(cmp_le_1), .S1(), .COUT());

    defparam g_cmp_ci_a.INJECT1_1 = "NO" ;
    defparam g_cmp_ci_a.INJECT1_0 = "NO" ;
    defparam g_cmp_ci_a.INIT1 =  16'h66AA ;
    defparam g_cmp_ci_a.INIT0 =  16'h66AA ;
    CCU2C g_cmp_ci_a (.A0(scuba_vhi), .A1(scuba_vhi), .B0(scuba_vhi), .B1(scuba_vhi), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(), .S0(), .S1(), .COUT(cmp_ci_1));

    defparam g_cmp_0.INJECT1_1 = "NO" ;
    defparam g_cmp_0.INJECT1_0 = "NO" ;
    defparam g_cmp_0.INIT1 =  16'h99AA ;
    defparam g_cmp_0.INIT0 =  16'h99AA ;
    CCU2C g_cmp_0 (.A0(fcount_0), .A1(fcount_1), .B0(wren_i), .B1(wren_i), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(cmp_ci_1), .S0(), .S1(), .COUT(co0_2));

    defparam g_cmp_1.INJECT1_1 = "NO" ;
    defparam g_cmp_1.INJECT1_0 = "NO" ;
    defparam g_cmp_1.INIT1 =  16'h99AA ;
    defparam g_cmp_1.INIT0 =  16'h99AA ;
    CCU2C g_cmp_1 (.A0(fcount_2), .A1(scuba_vlo), .B0(wren_i_inv), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co0_2), .S0(), .S1(), .COUT(cmp_ge_d1_c));

    defparam a1.INJECT1_1 = "NO" ;
    defparam a1.INJECT1_0 = "NO" ;
    defparam a1.INIT1 =  16'h66AA ;
    defparam a1.INIT0 =  16'h66AA ;
    CCU2C a1 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(cmp_ge_d1_c), .S0(cmp_ge_d1), .S1(), .COUT());

    defparam w_ctr_cia.INJECT1_1 = "NO" ;
    defparam w_ctr_cia.INJECT1_0 = "NO" ;
    defparam w_ctr_cia.INIT1 =  16'h66AA ;
    defparam w_ctr_cia.INIT0 =  16'h66AA ;
    CCU2C w_ctr_cia (.A0(scuba_vlo), .A1(scuba_vhi), .B0(scuba_vlo), .B1(scuba_vhi), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(), .S0(), .S1(), .COUT(w_ctr_ci));

    defparam w_ctr_0.INJECT1_1 = "NO" ;
    defparam w_ctr_0.INJECT1_0 = "NO" ;
    defparam w_ctr_0.INIT1 =  16'h66AA ;
    defparam w_ctr_0.INIT0 =  16'h66AA ;
    CCU2C w_ctr_0 (.A0(wcount_0), .A1(wcount_1), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(w_ctr_ci), .S0(iwcount_0), .S1(iwcount_1), .COUT(co0_3));

    defparam w_ctr_1.INJECT1_1 = "NO" ;
    defparam w_ctr_1.INJECT1_0 = "NO" ;
    defparam w_ctr_1.INIT1 =  16'h66AA ;
    defparam w_ctr_1.INIT0 =  16'h66AA ;
    CCU2C w_ctr_1 (.A0(wcount_2), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co0_3), .S0(iwcount_2), .S1(), .COUT(co1_1));

    defparam r_ctr_cia.INJECT1_1 = "NO" ;
    defparam r_ctr_cia.INJECT1_0 = "NO" ;
    defparam r_ctr_cia.INIT1 =  16'h66AA ;
    defparam r_ctr_cia.INIT0 =  16'h66AA ;
    CCU2C r_ctr_cia (.A0(scuba_vlo), .A1(scuba_vhi), .B0(scuba_vlo), .B1(scuba_vhi), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(), .S0(), .S1(), .COUT(r_ctr_ci));

    defparam r_ctr_0.INJECT1_1 = "NO" ;
    defparam r_ctr_0.INJECT1_0 = "NO" ;
    defparam r_ctr_0.INIT1 =  16'h66AA ;
    defparam r_ctr_0.INIT0 =  16'h66AA ;
    CCU2C r_ctr_0 (.A0(rcount_0), .A1(rcount_1), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(r_ctr_ci), .S0(ircount_0), .S1(ircount_1), .COUT(co0_4));

    defparam r_ctr_1.INJECT1_1 = "NO" ;
    defparam r_ctr_1.INJECT1_0 = "NO" ;
    defparam r_ctr_1.INIT1 =  16'h66AA ;
    defparam r_ctr_1.INIT0 =  16'h66AA ;
    CCU2C r_ctr_1 (.A0(rcount_2), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co0_4), .S0(ircount_2), .S1(), .COUT(co1_2));

    defparam ae_cmp_ci_a.INJECT1_1 = "NO" ;
    defparam ae_cmp_ci_a.INJECT1_0 = "NO" ;
    defparam ae_cmp_ci_a.INIT1 =  16'h66AA ;
    defparam ae_cmp_ci_a.INIT0 =  16'h66AA ;
    CCU2C ae_cmp_ci_a (.A0(scuba_vhi), .A1(scuba_vhi), .B0(scuba_vhi), .B1(scuba_vhi), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(), .S0(), .S1(), .COUT(cmp_ci_2));

    defparam ae_cmp_0.INJECT1_1 = "NO" ;
    defparam ae_cmp_0.INJECT1_0 = "NO" ;
    defparam ae_cmp_0.INIT1 =  16'h99AA ;
    defparam ae_cmp_0.INIT0 =  16'h99AA ;
    CCU2C ae_cmp_0 (.A0(fcnt_en_inv), .A1(r_nw), .B0(fcount_0), .B1(fcount_1), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(cmp_ci_2), .S0(), .S1(), .COUT(co0_5));

    defparam ae_cmp_1.INJECT1_1 = "NO" ;
    defparam ae_cmp_1.INJECT1_0 = "NO" ;
    defparam ae_cmp_1.INIT1 =  16'h99AA ;
    defparam ae_cmp_1.INIT0 =  16'h99AA ;
    CCU2C ae_cmp_1 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(fcount_2), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co0_5), .S0(), .S1(), .COUT(ae_d_c));

    defparam a2.INJECT1_1 = "NO" ;
    defparam a2.INJECT1_0 = "NO" ;
    defparam a2.INIT1 =  16'h66AA ;
    defparam a2.INIT0 =  16'h66AA ;
    CCU2C a2 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(ae_d_c), .S0(ae_d), .S1(), .COUT());

    defparam af_cmp_ci_a.INJECT1_1 = "NO" ;
    defparam af_cmp_ci_a.INJECT1_0 = "NO" ;
    defparam af_cmp_ci_a.INIT1 =  16'h66AA ;
    defparam af_cmp_ci_a.INIT0 =  16'h66AA ;
    CCU2C af_cmp_ci_a (.A0(scuba_vhi), .A1(scuba_vhi), .B0(scuba_vhi), .B1(scuba_vhi), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(), .S0(), .S1(), .COUT(cmp_ci_3));

    defparam af_cmp_0.INJECT1_1 = "NO" ;
    defparam af_cmp_0.INJECT1_0 = "NO" ;
    defparam af_cmp_0.INIT1 =  16'h99AA ;
    defparam af_cmp_0.INIT0 =  16'h99AA ;
    CCU2C af_cmp_0 (.A0(fcount_0), .A1(fcount_1), .B0(fcnt_en_inv), .B1(r_nw_inv), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(cmp_ci_3), .S0(), .S1(), .COUT(co0_6));

    defparam af_cmp_1.INJECT1_1 = "NO" ;
    defparam af_cmp_1.INJECT1_0 = "NO" ;
    defparam af_cmp_1.INIT1 =  16'h99AA ;
    defparam af_cmp_1.INIT0 =  16'h99AA ;
    CCU2C af_cmp_1 (.A0(fcount_2), .A1(scuba_vlo), .B0(r_nw), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co0_6), .S0(), .S1(), .COUT(af_d_c));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    defparam a3.INJECT1_1 = "NO" ;
    defparam a3.INJECT1_0 = "NO" ;
    defparam a3.INIT1 =  16'h66AA ;
    defparam a3.INIT0 =  16'h66AA ;
    CCU2C a3 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(af_d_c), .S0(af_d), .S1(), .COUT());

    defparam fifo_pfu_0_0.initval = "0x0000000000000000" ;
    DPR16X4C fifo_pfu_0_0 (.DI0(Data[12]), .DI1(Data[13]), .DI2(Data[14]), 
        .DI3(Data[15]), .WCK(Clock), .WRE(dec0_wre3), .RAD0(rcount_0), .RAD1(rcount_1), 
        .RAD2(scuba_vhi), .RAD3(scuba_vhi), .WAD0(wcount_0), .WAD1(wcount_1), 
        .WAD2(scuba_vhi), .WAD3(scuba_vhi), .DO0(rdataout12), .DO1(rdataout13), 
        .DO2(rdataout14), .DO3(rdataout15))
             /* synthesis MEM_INIT_FILE="(0-3)(0-3)" */
             /* synthesis MEM_LPC_FILE="pmi_fifoLLr1304416b8506c3__PMI__4__16__16A" */
             /* synthesis COMP="fifo_pfu_0_0" */;

    defparam fifo_pfu_0_1.initval = "0x0000000000000000" ;
    DPR16X4C fifo_pfu_0_1 (.DI0(Data[8]), .DI1(Data[9]), .DI2(Data[10]), 
        .DI3(Data[11]), .WCK(Clock), .WRE(dec0_wre3), .RAD0(rcount_0), .RAD1(rcount_1), 
        .RAD2(scuba_vhi), .RAD3(scuba_vhi), .WAD0(wcount_0), .WAD1(wcount_1), 
        .WAD2(scuba_vhi), .WAD3(scuba_vhi), .DO0(rdataout8), .DO1(rdataout9), 
        .DO2(rdataout10), .DO3(rdataout11))
             /* synthesis MEM_INIT_FILE="(0-3)(4-7)" */
             /* synthesis MEM_LPC_FILE="pmi_fifoLLr1304416b8506c3__PMI__4__16__16A" */
             /* synthesis COMP="fifo_pfu_0_1" */;

    defparam fifo_pfu_0_2.initval = "0x0000000000000000" ;
    DPR16X4C fifo_pfu_0_2 (.DI0(Data[4]), .DI1(Data[5]), .DI2(Data[6]), 
        .DI3(Data[7]), .WCK(Clock), .WRE(dec0_wre3), .RAD0(rcount_0), .RAD1(rcount_1), 
        .RAD2(scuba_vhi), .RAD3(scuba_vhi), .WAD0(wcount_0), .WAD1(wcount_1), 
        .WAD2(scuba_vhi), .WAD3(scuba_vhi), .DO0(rdataout4), .DO1(rdataout5), 
        .DO2(rdataout6), .DO3(rdataout7))
             /* synthesis MEM_INIT_FILE="(0-3)(8-11)" */
             /* synthesis MEM_LPC_FILE="pmi_fifoLLr1304416b8506c3__PMI__4__16__16A" */
             /* synthesis COMP="fifo_pfu_0_2" */;

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    defparam fifo_pfu_0_3.initval = "0x0000000000000000" ;
    DPR16X4C fifo_pfu_0_3 (.DI0(Data[0]), .DI1(Data[1]), .DI2(Data[2]), 
        .DI3(Data[3]), .WCK(Clock), .WRE(dec0_wre3), .RAD0(rcount_0), .RAD1(rcount_1), 
        .RAD2(scuba_vhi), .RAD3(scuba_vhi), .WAD0(wcount_0), .WAD1(wcount_1), 
        .WAD2(scuba_vhi), .WAD3(scuba_vhi), .DO0(rdataout0), .DO1(rdataout1), 
        .DO2(rdataout2), .DO3(rdataout3))
             /* synthesis MEM_INIT_FILE="(0-3)(12-15)" */
             /* synthesis MEM_LPC_FILE="pmi_fifoLLr1304416b8506c3__PMI__4__16__16A" */
             /* synthesis COMP="fifo_pfu_0_3" */;

    assign Empty = empty_i;
    assign Full = full_i;


    // exemplar begin
    // exemplar attribute FF_44 GSR ENABLED
    // exemplar attribute FF_43 GSR ENABLED
    // exemplar attribute FF_42 GSR ENABLED
    // exemplar attribute FF_41 GSR ENABLED
    // exemplar attribute FF_40 GSR ENABLED
    // exemplar attribute FF_39 GSR ENABLED
    // exemplar attribute FF_38 GSR ENABLED
    // exemplar attribute FF_37 GSR ENABLED
    // exemplar attribute FF_36 GSR ENABLED
    // exemplar attribute FF_35 GSR ENABLED
    // exemplar attribute FF_34 GSR ENABLED
    // exemplar attribute FF_33 GSR ENABLED
    // exemplar attribute FF_32 GSR ENABLED
    // exemplar attribute FF_31 GSR ENABLED
    // exemplar attribute FF_30 GSR ENABLED
    // exemplar attribute FF_29 GSR ENABLED
    // exemplar attribute FF_28 GSR ENABLED
    // exemplar attribute FF_27 GSR ENABLED
    // exemplar attribute FF_26 GSR ENABLED
    // exemplar attribute FF_25 GSR ENABLED
    // exemplar attribute FF_24 GSR ENABLED
    // exemplar attribute FF_23 GSR ENABLED
    // exemplar attribute FF_22 GSR ENABLED
    // exemplar attribute FF_21 GSR ENABLED
    // exemplar attribute FF_20 GSR ENABLED
    // exemplar attribute FF_19 GSR ENABLED
    // exemplar attribute FF_18 GSR ENABLED
    // exemplar attribute FF_17 GSR ENABLED
    // exemplar attribute FF_16 GSR ENABLED
    // exemplar attribute FF_15 GSR ENABLED
    // exemplar attribute FF_14 GSR ENABLED
    // exemplar attribute FF_13 GSR ENABLED
    // exemplar attribute FF_12 GSR ENABLED
    // exemplar attribute FF_11 GSR ENABLED
    // exemplar attribute FF_10 GSR ENABLED
    // exemplar attribute FF_9 GSR ENABLED
    // exemplar attribute FF_8 GSR ENABLED
    // exemplar attribute FF_7 GSR ENABLED
    // exemplar attribute FF_6 GSR ENABLED
    // exemplar attribute FF_5 GSR ENABLED
    // exemplar attribute FF_4 GSR ENABLED
    // exemplar attribute FF_3 GSR ENABLED
    // exemplar attribute FF_2 GSR ENABLED
    // exemplar attribute FF_1 GSR ENABLED
    // exemplar attribute FF_0 GSR ENABLED
    // exemplar attribute fifo_pfu_0_0 MEM_INIT_FILE (0-3)(0-3)
    // exemplar attribute fifo_pfu_0_0 MEM_LPC_FILE pmi_fifoLLr1304416b8506c3__PMI__4__16__16A
    // exemplar attribute fifo_pfu_0_0 COMP fifo_pfu_0_0
    // exemplar attribute fifo_pfu_0_1 MEM_INIT_FILE (0-3)(4-7)
    // exemplar attribute fifo_pfu_0_1 MEM_LPC_FILE pmi_fifoLLr1304416b8506c3__PMI__4__16__16A
    // exemplar attribute fifo_pfu_0_1 COMP fifo_pfu_0_1
    // exemplar attribute fifo_pfu_0_2 MEM_INIT_FILE (0-3)(8-11)
    // exemplar attribute fifo_pfu_0_2 MEM_LPC_FILE pmi_fifoLLr1304416b8506c3__PMI__4__16__16A
    // exemplar attribute fifo_pfu_0_2 COMP fifo_pfu_0_2
    // exemplar attribute fifo_pfu_0_3 MEM_INIT_FILE (0-3)(12-15)
    // exemplar attribute fifo_pfu_0_3 MEM_LPC_FILE pmi_fifoLLr1304416b8506c3__PMI__4__16__16A
    // exemplar attribute fifo_pfu_0_3 COMP fifo_pfu_0_3
    // exemplar end

endmodule
