/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 5.8 */
/* Sat Jun 28 17:35:31 2025 */

/* parameterized module instance */
mipi_rx __ (.clk_cd( ), .clk_n( ), .clk_p( ), .clk_rxhsen( ), 
    .clk_rxlpen( ), .clk_rxlpn( ), .clk_rxlpp( ), .clkhsbyte( ), 
    .d0_cd( ), .d0_hsdeseren( ), .d0_rxhsen( ), .d0_rxlpen( ), 
    .d0_rxlpn( ), .d0_rxlpp( ), .d0_txlpn( ), .d0_txlpp( ), 
    .rxhsbyteclk( ), .usrstdby( ), .data_n( ), .data_p( ), .q( ));
