/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 5.8 */
/* C:\lscc\diamond\3.12\ispfpga\bin\nt64\scuba.exe -w -n mipi_rx -lang verilog -synth lse -bus_exp 7 -bb -arch sn5w00 -type iol -io_type LVDS -mode MIPI -freq_in 600 -width 2 -app DSI_RX_H -gear 16 -fdc C:/Users/rui/Desktop/win10_crosslink/win10_test_mipi_v2/prj/mipi/mipi_rx/mipi_rx.fdc  */
/* Sat Jun 28 17:35:31 2025 */


`timescale 1 ns / 1 ps
module mipi_rx (clk_cd, clk_n, clk_p, clk_rxhsen, clk_rxlpen, clk_rxlpn, 
    clk_rxlpp, clkhsbyte, d0_cd, d0_hsdeseren, d0_rxhsen, d0_rxlpen, 
    d0_rxlpn, d0_rxlpp, d0_txlpn, d0_txlpp, rxhsbyteclk, usrstdby, 
    data_n, data_p, q)/* synthesis NGD_DRC_MASK=1 */;
    input wire clk_rxhsen;
    input wire clk_rxlpen;
    input wire d0_hsdeseren;
    input wire d0_rxhsen;
    input wire d0_rxlpen;
    input wire d0_txlpn;
    input wire d0_txlpp;
    input wire usrstdby;
    output wire clk_cd;
    output wire clk_rxlpn;
    output wire clk_rxlpp;
    output wire clkhsbyte;
    output wire d0_cd;
    output wire d0_rxlpn;
    output wire d0_rxlpp;
    output wire rxhsbyteclk;
    output wire [31:0] q;
    inout wire clk_n;
    inout wire clk_p;
    inout wire [1:0] data_n;
    inout wire [1:0] data_p;

    wire clk_rxhsen_inv;
    wire d0_rxlpen_inv;
    wire d0_rxhsen_inv;
    wire stop;
    wire reset;
    wire qa1;
    wire qb1;
    wire qc1;
    wire qd1;
    wire qe1;
    wire qf1;
    wire qg1;
    wire qh1;
    wire qi1;
    wire qj1;
    wire qk1;
    wire ql1;
    wire qm1;
    wire qn1;
    wire qo1;
    wire qp1;
    wire qa0;
    wire qb0;
    wire qc0;
    wire qd0;
    wire qe0;
    wire qf0;
    wire qg0;
    wire qh0;
    wire qi0;
    wire qj0;
    wire qk0;
    wire ql0;
    wire qm0;
    wire qn0;
    wire qo0;
    wire qp0;
    wire d0txlpen;
    wire d0_olsn;
    wire d0_olsp;
    wire d0rxlpen;
    wire scuba_vlo;
    wire scuba_vhi;
    wire clkrxlpen;

    OR2 OR2_t3 (.A(d0_olsp), .B(d0_olsn), .Z(d0_cd));

    INV INV_2 (.A(clk_rxhsen), .Z(clk_rxhsen_inv));

    AND2 AND2_t2 (.A(clk_rxhsen_inv), .B(clk_rxlpen), .Z(clkrxlpen));

    INV INV_1 (.A(d0_rxhsen), .Z(d0_rxhsen_inv));

    AND2 AND2_t1 (.A(d0_rxhsen_inv), .B(d0_rxlpen), .Z(d0rxlpen));

    INV INV_0 (.A(d0_rxlpen), .Z(d0_rxlpen_inv));

    AND2 AND2_t0 (.A(d0_rxhsen_inv), .B(d0_rxlpen_inv), .Z(d0txlpen));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    defparam Inst_MIPIDPHYA.HS_16BIT_EN = 1 ;
    defparam Inst_MIPIDPHYA.HSEL = 1 ;
    defparam Inst_MIPIDPHYA.CO = 0 ;
    defparam Inst_MIPIDPHYA.CM = 0 ;
    defparam Inst_MIPIDPHYA.CN = 0 ;
    MIPIDPHYA Inst_MIPIDPHYA (.CKP(clk_p), .CKN(clk_n), .CLKHSBYTE(clkhsbyte), 
        .CLKRXHSEN(clk_rxhsen), .CLKDRXLPP(clk_rxlpp), .CLKRXLPEN(clkrxlpen), 
        .CLKDRXLPN(clk_rxlpn), .CLKCDEN(scuba_vhi), .CLKDCDN(clk_cd), .CLKDTXLPP(scuba_vlo), 
        .CLKTXLPEN(scuba_vlo), .CLKDTXLPN(scuba_vlo), .CLKTXHSEN(scuba_vlo), 
        .CLKTXHSGATE(scuba_vlo), .CLKTXHSPD(scuba_vhi), .CLKDRXHS(), .HSBYTECLKD(rxhsbyteclk), 
        .HSBYTECLKS(), .LBEN(scuba_vlo), .PDDPHY(usrstdby), .PDBIAS(scuba_vlo), 
        .PDCKG(scuba_vlo), .CLKREF(scuba_vlo), .LOCK(), .PDPLL(scuba_vhi), 
        .DP0(data_p[0]), .DP1(data_p[1]), .DP2(), .DP3(), .DN0(data_n[0]), 
        .DN1(data_n[1]), .DN2(), .DN3(), .D0DRXLPP(d0_rxlpp), .D0RXLPEN(d0rxlpen), 
        .D0DRXLPN(d0_rxlpn), .D0DCDP(d0_olsp), .D0CDEN(scuba_vhi), .D0DCDN(d0_olsn), 
        .D0DTXLPP(d0_txlpp), .D0TXLPEN(d0txlpen), .D0DTXLPN(d0_txlpn), .D0RXHSEN(d0_rxhsen), 
        .D0HSRXDATA15(qp0), .D0HSRXDATA14(qo0), .D0HSRXDATA13(qn0), .D0HSRXDATA12(qm0), 
        .D0HSRXDATA11(ql0), .D0HSRXDATA10(qk0), .D0HSRXDATA9(qj0), .D0HSRXDATA8(qi0), 
        .D0HSRXDATA7(qh0), .D0HSRXDATA6(qg0), .D0HSRXDATA5(qf0), .D0HSRXDATA4(qe0), 
        .D0HSRXDATA3(qd0), .D0HSRXDATA2(qc0), .D0HSRXDATA1(qb0), .D0HSRXDATA0(qa0), 
        .D0SYNC(), .D0ERRSYNC(), .D0NOSYNC(), .D0HSDESEREN(d0_hsdeseren), 
        .D0TXHSEN(scuba_vlo), .D0HSTXDATA15(scuba_vlo), .D0HSTXDATA14(scuba_vlo), 
        .D0HSTXDATA13(scuba_vlo), .D0HSTXDATA12(scuba_vlo), .D0HSTXDATA11(scuba_vlo), 
        .D0HSTXDATA10(scuba_vlo), .D0HSTXDATA9(scuba_vlo), .D0HSTXDATA8(scuba_vlo), 
        .D0HSTXDATA7(scuba_vlo), .D0HSTXDATA6(scuba_vlo), .D0HSTXDATA5(scuba_vlo), 
        .D0HSTXDATA4(scuba_vlo), .D0HSTXDATA3(scuba_vlo), .D0HSTXDATA2(scuba_vlo), 
        .D0HSTXDATA1(scuba_vlo), .D0HSTXDATA0(scuba_vlo), .D0HSSEREN(scuba_vlo), 
        .D0TXHSPD(scuba_vhi), .D0DRXHS(), .D1DRXLPP(), .D1RXLPEN(d0rxlpen), 
        .D1DRXLPN(), .D1DCDP(), .D1CDEN(scuba_vlo), .D1DCDN(), .D1DTXLPP(scuba_vlo), 
        .D1TXLPEN(scuba_vlo), .D1DTXLPN(scuba_vlo), .D1RXHSEN(d0_rxhsen), 
        .D1HSRXDATA15(qp1), .D1HSRXDATA14(qo1), .D1HSRXDATA13(qn1), .D1HSRXDATA12(qm1), 
        .D1HSRXDATA11(ql1), .D1HSRXDATA10(qk1), .D1HSRXDATA9(qj1), .D1HSRXDATA8(qi1), 
        .D1HSRXDATA7(qh1), .D1HSRXDATA6(qg1), .D1HSRXDATA5(qf1), .D1HSRXDATA4(qe1), 
        .D1HSRXDATA3(qd1), .D1HSRXDATA2(qc1), .D1HSRXDATA1(qb1), .D1HSRXDATA0(qa1), 
        .D1SYNC(), .D1ERRSYNC(), .D1NOSYNC(), .D1HSDESEREN(d0_hsdeseren), 
        .D1TXHSEN(scuba_vlo), .D1HSTXDATA15(scuba_vlo), .D1HSTXDATA14(scuba_vlo), 
        .D1HSTXDATA13(scuba_vlo), .D1HSTXDATA12(scuba_vlo), .D1HSTXDATA11(scuba_vlo), 
        .D1HSTXDATA10(scuba_vlo), .D1HSTXDATA9(scuba_vlo), .D1HSTXDATA8(scuba_vlo), 
        .D1HSTXDATA7(scuba_vlo), .D1HSTXDATA6(scuba_vlo), .D1HSTXDATA5(scuba_vlo), 
        .D1HSTXDATA4(scuba_vlo), .D1HSTXDATA3(scuba_vlo), .D1HSTXDATA2(scuba_vlo), 
        .D1HSTXDATA1(scuba_vlo), .D1HSTXDATA0(scuba_vlo), .D1HSSEREN(scuba_vlo), 
        .D1TXHSPD(scuba_vhi), .D1DRXHS(), .D2DRXLPP(), .D2RXLPEN(scuba_vlo), 
        .D2DRXLPN(), .D2DCDP(), .D2CDEN(scuba_vlo), .D2DCDN(), .D2DTXLPP(scuba_vlo), 
        .D2TXLPEN(scuba_vlo), .D2DTXLPN(scuba_vlo), .D2RXHSEN(scuba_vlo), 
        .D2HSRXDATA15(), .D2HSRXDATA14(), .D2HSRXDATA13(), .D2HSRXDATA12(), 
        .D2HSRXDATA11(), .D2HSRXDATA10(), .D2HSRXDATA9(), .D2HSRXDATA8(), 
        .D2HSRXDATA7(), .D2HSRXDATA6(), .D2HSRXDATA5(), .D2HSRXDATA4(), 
        .D2HSRXDATA3(), .D2HSRXDATA2(), .D2HSRXDATA1(), .D2HSRXDATA0(), 
        .D2SYNC(), .D2ERRSYNC(), .D2NOSYNC(), .D2HSDESEREN(scuba_vlo), .D2TXHSEN(scuba_vlo), 
        .D2HSTXDATA15(scuba_vlo), .D2HSTXDATA14(scuba_vlo), .D2HSTXDATA13(scuba_vlo), 
        .D2HSTXDATA12(scuba_vlo), .D2HSTXDATA11(scuba_vlo), .D2HSTXDATA10(scuba_vlo), 
        .D2HSTXDATA9(scuba_vlo), .D2HSTXDATA8(scuba_vlo), .D2HSTXDATA7(scuba_vlo), 
        .D2HSTXDATA6(scuba_vlo), .D2HSTXDATA5(scuba_vlo), .D2HSTXDATA4(scuba_vlo), 
        .D2HSTXDATA3(scuba_vlo), .D2HSTXDATA2(scuba_vlo), .D2HSTXDATA1(scuba_vlo), 
        .D2HSTXDATA0(scuba_vlo), .D2HSSEREN(scuba_vlo), .D2TXHSPD(scuba_vhi), 
        .D2DRXHS(), .D3DRXLPP(), .D3RXLPEN(scuba_vlo), .D3DRXLPN(), .D3DCDP(), 
        .D3CDEN(scuba_vlo), .D3DCDN(), .D3DTXLPP(scuba_vlo), .D3TXLPEN(scuba_vlo), 
        .D3DTXLPN(scuba_vlo), .D3RXHSEN(scuba_vlo), .D3HSRXDATA15(), .D3HSRXDATA14(), 
        .D3HSRXDATA13(), .D3HSRXDATA12(), .D3HSRXDATA11(), .D3HSRXDATA10(), 
        .D3HSRXDATA9(), .D3HSRXDATA8(), .D3HSRXDATA7(), .D3HSRXDATA6(), 
        .D3HSRXDATA5(), .D3HSRXDATA4(), .D3HSRXDATA3(), .D3HSRXDATA2(), 
        .D3HSRXDATA1(), .D3HSRXDATA0(), .D3SYNC(), .D3ERRSYNC(), .D3NOSYNC(), 
        .D3HSDESEREN(scuba_vlo), .D3TXHSEN(scuba_vlo), .D3HSTXDATA15(scuba_vlo), 
        .D3HSTXDATA14(scuba_vlo), .D3HSTXDATA13(scuba_vlo), .D3HSTXDATA12(scuba_vlo), 
        .D3HSTXDATA11(scuba_vlo), .D3HSTXDATA10(scuba_vlo), .D3HSTXDATA9(scuba_vlo), 
        .D3HSTXDATA8(scuba_vlo), .D3HSTXDATA7(scuba_vlo), .D3HSTXDATA6(scuba_vlo), 
        .D3HSTXDATA5(scuba_vlo), .D3HSTXDATA4(scuba_vlo), .D3HSTXDATA3(scuba_vlo), 
        .D3HSTXDATA2(scuba_vlo), .D3HSTXDATA1(scuba_vlo), .D3HSTXDATA0(scuba_vlo), 
        .D3HSSEREN(scuba_vlo), .D3TXHSPD(scuba_vhi), .D3DRXHS())
             /* synthesis HS_MODE="RX" */
             /* synthesis DIR_PIN_DN1="INPUT" */
             /* synthesis DIR_PIN_DP1="INPUT" */
             /* synthesis DIR_PIN_CKN="INPUT" */
             /* synthesis DIR_PIN_CKP="INPUT" */
             /* synthesis FREQUENCY_PIN_HSBYTECLKD="75.000000" */;

    assign stop = reset;
    assign q[31] = qp1;
    assign q[30] = qp0;
    assign q[29] = qo1;
    assign q[28] = qo0;
    assign q[27] = qn1;
    assign q[26] = qn0;
    assign q[25] = qm1;
    assign q[24] = qm0;
    assign q[23] = ql1;
    assign q[22] = ql0;
    assign q[21] = qk1;
    assign q[20] = qk0;
    assign q[19] = qj1;
    assign q[18] = qj0;
    assign q[17] = qi1;
    assign q[16] = qi0;
    assign q[15] = qh1;
    assign q[14] = qh0;
    assign q[13] = qg1;
    assign q[12] = qg0;
    assign q[11] = qf1;
    assign q[10] = qf0;
    assign q[9] = qe1;
    assign q[8] = qe0;
    assign q[7] = qd1;
    assign q[6] = qd0;
    assign q[5] = qc1;
    assign q[4] = qc0;
    assign q[3] = qb1;
    assign q[2] = qb0;
    assign q[1] = qa1;
    assign q[0] = qa0;


    // exemplar begin
    // exemplar attribute Inst_MIPIDPHYA HS_MODE RX
    // exemplar attribute Inst_MIPIDPHYA DIR_PIN_DN1 INPUT
    // exemplar attribute Inst_MIPIDPHYA DIR_PIN_DP1 INPUT
    // exemplar attribute Inst_MIPIDPHYA DIR_PIN_CKN INPUT
    // exemplar attribute Inst_MIPIDPHYA DIR_PIN_CKP INPUT
    // exemplar attribute Inst_MIPIDPHYA FREQUENCY_PIN_HSBYTECLKD 75.000000
    // exemplar end

endmodule
