-d C:\Users\rui\Desktop\iphone7-lcd-reverse-engineering\touch\logic_level_shifter_33_18\impl\gwsynthesis\logic_level_shifter_33_18.vg
-p GW1NSR-4C-QFN48P-6
-pn GW1NSR-LV4CQN48PC6/I5
-cst C:\Users\rui\Desktop\iphone7-lcd-reverse-engineering\touch\logic_level_shifter_33_18\src\logic_level_shifter_33_18.cst
-cfg C:\Users\rui\Desktop\iphone7-lcd-reverse-engineering\touch\logic_level_shifter_33_18\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
