/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 5.8 */
/* Sun Jun 29 01:16:37 2025 */

/* parameterized module instance */
dphy_raw_fifo __ (.Data( ), .WrClock( ), .RdClock( ), .WrEn( ), .RdEn( ), 
    .Reset( ), .RPReset( ), .Q( ), .WCNT( ), .RCNT( ), .Empty( ), 
    .Full( ));
