/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 5.8 */
/* C:\lscc\diamond\3.12\ispfpga\bin\nt64\scuba.exe -w -n dphy_raw_fifo -lang verilog -synth lse -bus_exp 7 -bb -arch sn5w00 -type ebfifo -depth 32 -width 32 -rwidth 32 -reset_rel SYNC -pe -1 -pf -1 -rfill -fill -fdc C:/Users/rui/Desktop/win10_crosslink/win10_test_mipi_v2/ip/fifo/dphy_raw_fifo/dphy_raw_fifo.fdc  */
/* Sun Jun 29 01:16:37 2025 */


`timescale 1 ns / 1 ps
module dphy_raw_fifo (Data, WrClock, RdClock, WrEn, RdEn, Reset, RPReset, 
    Q, WCNT, RCNT, Empty, Full)/* synthesis NGD_DRC_MASK=1 */;
    input wire [31:0] Data;
    input wire WrClock;
    input wire RdClock;
    input wire WrEn;
    input wire RdEn;
    input wire Reset;
    input wire RPReset;
    output wire [31:0] Q;
    output wire [5:0] WCNT;
    output wire [5:0] RCNT;
    output wire Empty;
    output wire Full;

    wire invout_1;
    wire invout_0;
    wire w_gdata_0;
    wire w_gdata_1;
    wire w_gdata_2;
    wire w_gdata_3;
    wire w_gdata_4;
    wire wptr_5;
    wire r_gdata_0;
    wire r_gdata_1;
    wire r_gdata_2;
    wire r_gdata_3;
    wire r_gdata_4;
    wire rptr_5;
    wire w_gcount_0;
    wire w_gcount_1;
    wire w_gcount_2;
    wire w_gcount_3;
    wire w_gcount_4;
    wire w_gcount_5;
    wire r_gcount_0;
    wire r_gcount_1;
    wire r_gcount_2;
    wire r_gcount_3;
    wire r_gcount_4;
    wire r_gcount_5;
    wire w_gcount_r20;
    wire w_gcount_r0;
    wire w_gcount_r21;
    wire w_gcount_r1;
    wire w_gcount_r22;
    wire w_gcount_r2;
    wire w_gcount_r23;
    wire w_gcount_r3;
    wire w_gcount_r24;
    wire w_gcount_r4;
    wire w_gcount_r25;
    wire w_gcount_r5;
    wire r_gcount_w20;
    wire r_gcount_w0;
    wire r_gcount_w21;
    wire r_gcount_w1;
    wire r_gcount_w22;
    wire r_gcount_w2;
    wire r_gcount_w23;
    wire r_gcount_w3;
    wire r_gcount_w24;
    wire r_gcount_w4;
    wire r_gcount_w25;
    wire r_gcount_w5;
    wire empty_i;
    wire rRst;
    wire full_i;
    wire iwcount_0;
    wire iwcount_1;
    wire w_gctr_ci;
    wire iwcount_2;
    wire iwcount_3;
    wire co0;
    wire iwcount_4;
    wire iwcount_5;
    wire co2;
    wire co1;
    wire wcount_5;
    wire ircount_0;
    wire ircount_1;
    wire r_gctr_ci;
    wire ircount_2;
    wire ircount_3;
    wire co0_1;
    wire ircount_4;
    wire ircount_5;
    wire co2_1;
    wire co1_1;
    wire rcount_5;
    wire wfill_sub_0;
    wire wptr_0;
    wire precin;
    wire wfill_sub_1;
    wire wfill_sub_2;
    wire wptr_2;
    wire wptr_1;
    wire co0_2;
    wire wfill_sub_3;
    wire wfill_sub_4;
    wire wptr_4;
    wire wptr_3;
    wire co1_2;
    wire wfill_sub_5;
    wire wfill_sub_msb;
    wire co2_2;
    wire rfill_sub_0;
    wire rptr_0;
    wire precin_1;
    wire rfill_sub_1;
    wire rfill_sub_2;
    wire rptr_2;
    wire rptr_1;
    wire co0_3;
    wire rfill_sub_3;
    wire rfill_sub_4;
    wire rptr_4;
    wire rptr_3;
    wire co1_3;
    wire rfill_sub_5;
    wire rfill_sub_msb;
    wire co2_3;
    wire rden_i;
    wire cmp_ci;
    wire wcount_r0;
    wire wcount_r1;
    wire rcount_0;
    wire rcount_1;
    wire co0_4;
    wire w_g2b_xor_cluster_0;
    wire wcount_r3;
    wire rcount_2;
    wire rcount_3;
    wire co1_4;
    wire wcount_r4;
    wire empty_cmp_clr;
    wire rcount_4;
    wire empty_cmp_set;
    wire empty_d;
    wire empty_d_c;
    wire wren_i;
    wire cmp_ci_1;
    wire rcount_w0;
    wire rcount_w1;
    wire wcount_0;
    wire wcount_1;
    wire co0_5;
    wire r_g2b_xor_cluster_0;
    wire rcount_w3;
    wire wcount_2;
    wire wcount_3;
    wire co1_5;
    wire rcount_w4;
    wire full_cmp_clr;
    wire wcount_4;
    wire full_cmp_set;
    wire full_d;
    wire scuba_vhi;
    wire scuba_vlo;
    wire full_d_c;

    AND2 AND2_t14 (.A(WrEn), .B(invout_1), .Z(wren_i));

    INV INV_1 (.A(full_i), .Z(invout_1));

    AND2 AND2_t13 (.A(RdEn), .B(invout_0), .Z(rden_i));

    INV INV_0 (.A(empty_i), .Z(invout_0));

    OR2 OR2_t12 (.A(Reset), .B(RPReset), .Z(rRst));

    XOR2 XOR2_t11 (.A(wcount_0), .B(wcount_1), .Z(w_gdata_0));

    XOR2 XOR2_t10 (.A(wcount_1), .B(wcount_2), .Z(w_gdata_1));

    XOR2 XOR2_t9 (.A(wcount_2), .B(wcount_3), .Z(w_gdata_2));

    XOR2 XOR2_t8 (.A(wcount_3), .B(wcount_4), .Z(w_gdata_3));

    XOR2 XOR2_t7 (.A(wcount_4), .B(wcount_5), .Z(w_gdata_4));

    XOR2 XOR2_t6 (.A(rcount_0), .B(rcount_1), .Z(r_gdata_0));

    XOR2 XOR2_t5 (.A(rcount_1), .B(rcount_2), .Z(r_gdata_1));

    XOR2 XOR2_t4 (.A(rcount_2), .B(rcount_3), .Z(r_gdata_2));

    XOR2 XOR2_t3 (.A(rcount_3), .B(rcount_4), .Z(r_gdata_3));

    XOR2 XOR2_t2 (.A(rcount_4), .B(rcount_5), .Z(r_gdata_4));

    defparam LUT4_13.initval =  16'h6996 ;
    ROM16X1A LUT4_13 (.AD3(w_gcount_r22), .AD2(w_gcount_r23), .AD1(w_gcount_r24), 
        .AD0(w_gcount_r25), .DO0(w_g2b_xor_cluster_0));

    defparam LUT4_12.initval =  16'h6996 ;
    ROM16X1A LUT4_12 (.AD3(w_gcount_r24), .AD2(w_gcount_r25), .AD1(scuba_vlo), 
        .AD0(scuba_vlo), .DO0(wcount_r4));

    defparam LUT4_11.initval =  16'h6996 ;
    ROM16X1A LUT4_11 (.AD3(w_gcount_r23), .AD2(w_gcount_r24), .AD1(w_gcount_r25), 
        .AD0(scuba_vlo), .DO0(wcount_r3));

    defparam LUT4_10.initval =  16'h6996 ;
    ROM16X1A LUT4_10 (.AD3(w_gcount_r21), .AD2(w_gcount_r22), .AD1(w_gcount_r23), 
        .AD0(wcount_r4), .DO0(wcount_r1));

    defparam LUT4_9.initval =  16'h6996 ;
    ROM16X1A LUT4_9 (.AD3(w_gcount_r20), .AD2(w_gcount_r21), .AD1(w_gcount_r22), 
        .AD0(wcount_r3), .DO0(wcount_r0));

    defparam LUT4_8.initval =  16'h6996 ;
    ROM16X1A LUT4_8 (.AD3(r_gcount_w22), .AD2(r_gcount_w23), .AD1(r_gcount_w24), 
        .AD0(r_gcount_w25), .DO0(r_g2b_xor_cluster_0));

    defparam LUT4_7.initval =  16'h6996 ;
    ROM16X1A LUT4_7 (.AD3(r_gcount_w24), .AD2(r_gcount_w25), .AD1(scuba_vlo), 
        .AD0(scuba_vlo), .DO0(rcount_w4));

    defparam LUT4_6.initval =  16'h6996 ;
    ROM16X1A LUT4_6 (.AD3(r_gcount_w23), .AD2(r_gcount_w24), .AD1(r_gcount_w25), 
        .AD0(scuba_vlo), .DO0(rcount_w3));

    defparam LUT4_5.initval =  16'h6996 ;
    ROM16X1A LUT4_5 (.AD3(r_gcount_w21), .AD2(r_gcount_w22), .AD1(r_gcount_w23), 
        .AD0(rcount_w4), .DO0(rcount_w1));

    defparam LUT4_4.initval =  16'h6996 ;
    ROM16X1A LUT4_4 (.AD3(r_gcount_w20), .AD2(r_gcount_w21), .AD1(r_gcount_w22), 
        .AD0(rcount_w3), .DO0(rcount_w0));

    XOR2 XOR2_t1 (.A(wptr_5), .B(r_gcount_w25), .Z(wfill_sub_msb));

    XOR2 XOR2_t0 (.A(w_gcount_r25), .B(rptr_5), .Z(rfill_sub_msb));

    defparam LUT4_3.initval =  16'h0410 ;
    ROM16X1A LUT4_3 (.AD3(rptr_5), .AD2(rcount_5), .AD1(w_gcount_r25), .AD0(scuba_vlo), 
        .DO0(empty_cmp_set));

    defparam LUT4_2.initval =  16'h1004 ;
    ROM16X1A LUT4_2 (.AD3(rptr_5), .AD2(rcount_5), .AD1(w_gcount_r25), .AD0(scuba_vlo), 
        .DO0(empty_cmp_clr));

    defparam LUT4_1.initval =  16'h0140 ;
    ROM16X1A LUT4_1 (.AD3(wptr_5), .AD2(wcount_5), .AD1(r_gcount_w25), .AD0(scuba_vlo), 
        .DO0(full_cmp_set));

    defparam LUT4_0.initval =  16'h4001 ;
    ROM16X1A LUT4_0 (.AD3(wptr_5), .AD2(wcount_5), .AD1(r_gcount_w25), .AD0(scuba_vlo), 
        .DO0(full_cmp_clr));

    defparam pdp_ram_0_0_1.INIT_DATA = "STATIC" ;
    defparam pdp_ram_0_0_1.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam pdp_ram_0_0_1.CSDECODE_R = "0b000" ;
    defparam pdp_ram_0_0_1.CSDECODE_W = "0b001" ;
    defparam pdp_ram_0_0_1.GSR = "ENABLED" ;
    defparam pdp_ram_0_0_1.RESETMODE = "ASYNC" ;
    defparam pdp_ram_0_0_1.REGMODE = "NOREG" ;
    defparam pdp_ram_0_0_1.DATA_WIDTH_R = 18 ;
    defparam pdp_ram_0_0_1.DATA_WIDTH_W = 18 ;
    PDPW8KE pdp_ram_0_0_1 (.DI17(Data[17]), .DI16(Data[16]), .DI15(Data[15]), 
        .DI14(Data[14]), .DI13(Data[13]), .DI12(Data[12]), .DI11(Data[11]), 
        .DI10(Data[10]), .DI9(Data[9]), .DI8(Data[8]), .DI7(Data[7]), .DI6(Data[6]), 
        .DI5(Data[5]), .DI4(Data[4]), .DI3(Data[3]), .DI2(Data[2]), .DI1(Data[1]), 
        .DI0(Data[0]), .ADW8(scuba_vlo), .ADW7(scuba_vlo), .ADW6(scuba_vlo), 
        .ADW5(scuba_vlo), .ADW4(wptr_4), .ADW3(wptr_3), .ADW2(wptr_2), .ADW1(wptr_1), 
        .ADW0(wptr_0), .BE1(scuba_vhi), .BE0(scuba_vhi), .CEW(wren_i), .CLKW(WrClock), 
        .CSW2(scuba_vlo), .CSW1(scuba_vlo), .CSW0(scuba_vhi), .ADR12(scuba_vlo), 
        .ADR11(scuba_vlo), .ADR10(scuba_vlo), .ADR9(scuba_vlo), .ADR8(rptr_4), 
        .ADR7(rptr_3), .ADR6(rptr_2), .ADR5(rptr_1), .ADR4(rptr_0), .ADR3(scuba_vlo), 
        .ADR2(scuba_vlo), .ADR1(scuba_vlo), .ADR0(scuba_vlo), .CER(rden_i), 
        .OCER(rden_i), .CLKR(RdClock), .CSR2(scuba_vlo), .CSR1(scuba_vlo), 
        .CSR0(scuba_vlo), .RST(Reset), .DO17(Q[8]), .DO16(Q[7]), .DO15(Q[6]), 
        .DO14(Q[5]), .DO13(Q[4]), .DO12(Q[3]), .DO11(Q[2]), .DO10(Q[1]), 
        .DO9(Q[0]), .DO8(Q[17]), .DO7(Q[16]), .DO6(Q[15]), .DO5(Q[14]), 
        .DO4(Q[13]), .DO3(Q[12]), .DO2(Q[11]), .DO1(Q[10]), .DO0(Q[9]))
             /* synthesis MEM_LPC_FILE="dphy_raw_fifo.lpc" */
             /* synthesis MEM_INIT_FILE="" */;

    defparam pdp_ram_0_1_0.INIT_DATA = "STATIC" ;
    defparam pdp_ram_0_1_0.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam pdp_ram_0_1_0.CSDECODE_R = "0b000" ;
    defparam pdp_ram_0_1_0.CSDECODE_W = "0b001" ;
    defparam pdp_ram_0_1_0.GSR = "ENABLED" ;
    defparam pdp_ram_0_1_0.RESETMODE = "ASYNC" ;
    defparam pdp_ram_0_1_0.REGMODE = "NOREG" ;
    defparam pdp_ram_0_1_0.DATA_WIDTH_R = 18 ;
    defparam pdp_ram_0_1_0.DATA_WIDTH_W = 18 ;
    PDPW8KE pdp_ram_0_1_0 (.DI17(scuba_vlo), .DI16(scuba_vlo), .DI15(scuba_vlo), 
        .DI14(scuba_vlo), .DI13(Data[31]), .DI12(Data[30]), .DI11(Data[29]), 
        .DI10(Data[28]), .DI9(Data[27]), .DI8(Data[26]), .DI7(Data[25]), 
        .DI6(Data[24]), .DI5(Data[23]), .DI4(Data[22]), .DI3(Data[21]), 
        .DI2(Data[20]), .DI1(Data[19]), .DI0(Data[18]), .ADW8(scuba_vlo), 
        .ADW7(scuba_vlo), .ADW6(scuba_vlo), .ADW5(scuba_vlo), .ADW4(wptr_4), 
        .ADW3(wptr_3), .ADW2(wptr_2), .ADW1(wptr_1), .ADW0(wptr_0), .BE1(scuba_vhi), 
        .BE0(scuba_vhi), .CEW(wren_i), .CLKW(WrClock), .CSW2(scuba_vlo), 
        .CSW1(scuba_vlo), .CSW0(scuba_vhi), .ADR12(scuba_vlo), .ADR11(scuba_vlo), 
        .ADR10(scuba_vlo), .ADR9(scuba_vlo), .ADR8(rptr_4), .ADR7(rptr_3), 
        .ADR6(rptr_2), .ADR5(rptr_1), .ADR4(rptr_0), .ADR3(scuba_vlo), .ADR2(scuba_vlo), 
        .ADR1(scuba_vlo), .ADR0(scuba_vlo), .CER(rden_i), .OCER(rden_i), 
        .CLKR(RdClock), .CSR2(scuba_vlo), .CSR1(scuba_vlo), .CSR0(scuba_vlo), 
        .RST(Reset), .DO17(Q[26]), .DO16(Q[25]), .DO15(Q[24]), .DO14(Q[23]), 
        .DO13(Q[22]), .DO12(Q[21]), .DO11(Q[20]), .DO10(Q[19]), .DO9(Q[18]), 
        .DO8(), .DO7(), .DO6(), .DO5(), .DO4(Q[31]), .DO3(Q[30]), .DO2(Q[29]), 
        .DO1(Q[28]), .DO0(Q[27]))
             /* synthesis MEM_LPC_FILE="dphy_raw_fifo.lpc" */
             /* synthesis MEM_INIT_FILE="" */;

    FD1P3BX FF_73 (.D(iwcount_0), .SP(wren_i), .CK(WrClock), .PD(Reset), 
        .Q(wcount_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_72 (.D(iwcount_1), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_71 (.D(iwcount_2), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_70 (.D(iwcount_3), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_69 (.D(iwcount_4), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_68 (.D(iwcount_5), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_67 (.D(w_gdata_0), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_66 (.D(w_gdata_1), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_65 (.D(w_gdata_2), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_64 (.D(w_gdata_3), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_63 (.D(w_gdata_4), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_62 (.D(wcount_5), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_61 (.D(wcount_0), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_60 (.D(wcount_1), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_59 (.D(wcount_2), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_58 (.D(wcount_3), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_57 (.D(wcount_4), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_56 (.D(wcount_5), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3BX FF_55 (.D(ircount_0), .SP(rden_i), .CK(RdClock), .PD(rRst), 
        .Q(rcount_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_54 (.D(ircount_1), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_53 (.D(ircount_2), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_52 (.D(ircount_3), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_51 (.D(ircount_4), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_50 (.D(ircount_5), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_49 (.D(r_gdata_0), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_48 (.D(r_gdata_1), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_47 (.D(r_gdata_2), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_46 (.D(r_gdata_3), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_45 (.D(r_gdata_4), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_44 (.D(rcount_5), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(r_gcount_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_43 (.D(rcount_0), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_42 (.D(rcount_1), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_41 (.D(rcount_2), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_40 (.D(rcount_3), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_39 (.D(rcount_4), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_38 (.D(rcount_5), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_5))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_37 (.D(w_gcount_0), .CK(RdClock), .CD(Reset), .Q(w_gcount_r0))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_36 (.D(w_gcount_1), .CK(RdClock), .CD(Reset), .Q(w_gcount_r1))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_35 (.D(w_gcount_2), .CK(RdClock), .CD(Reset), .Q(w_gcount_r2))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_34 (.D(w_gcount_3), .CK(RdClock), .CD(Reset), .Q(w_gcount_r3))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_33 (.D(w_gcount_4), .CK(RdClock), .CD(Reset), .Q(w_gcount_r4))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_32 (.D(w_gcount_5), .CK(RdClock), .CD(Reset), .Q(w_gcount_r5))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_31 (.D(r_gcount_0), .CK(WrClock), .CD(rRst), .Q(r_gcount_w0))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_30 (.D(r_gcount_1), .CK(WrClock), .CD(rRst), .Q(r_gcount_w1))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_29 (.D(r_gcount_2), .CK(WrClock), .CD(rRst), .Q(r_gcount_w2))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_28 (.D(r_gcount_3), .CK(WrClock), .CD(rRst), .Q(r_gcount_w3))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_27 (.D(r_gcount_4), .CK(WrClock), .CD(rRst), .Q(r_gcount_w4))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_26 (.D(r_gcount_5), .CK(WrClock), .CD(rRst), .Q(r_gcount_w5))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_25 (.D(w_gcount_r0), .CK(RdClock), .CD(Reset), .Q(w_gcount_r20))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_24 (.D(w_gcount_r1), .CK(RdClock), .CD(Reset), .Q(w_gcount_r21))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_23 (.D(w_gcount_r2), .CK(RdClock), .CD(Reset), .Q(w_gcount_r22))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_22 (.D(w_gcount_r3), .CK(RdClock), .CD(Reset), .Q(w_gcount_r23))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_21 (.D(w_gcount_r4), .CK(RdClock), .CD(Reset), .Q(w_gcount_r24))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_20 (.D(w_gcount_r5), .CK(RdClock), .CD(Reset), .Q(w_gcount_r25))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_19 (.D(r_gcount_w0), .CK(WrClock), .CD(rRst), .Q(r_gcount_w20))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_18 (.D(r_gcount_w1), .CK(WrClock), .CD(rRst), .Q(r_gcount_w21))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_17 (.D(r_gcount_w2), .CK(WrClock), .CD(rRst), .Q(r_gcount_w22))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_16 (.D(r_gcount_w3), .CK(WrClock), .CD(rRst), .Q(r_gcount_w23))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_15 (.D(r_gcount_w4), .CK(WrClock), .CD(rRst), .Q(r_gcount_w24))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_14 (.D(r_gcount_w5), .CK(WrClock), .CD(rRst), .Q(r_gcount_w25))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_13 (.D(wfill_sub_0), .CK(WrClock), .CD(Reset), .Q(WCNT[0]))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_12 (.D(wfill_sub_1), .CK(WrClock), .CD(Reset), .Q(WCNT[1]))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_11 (.D(wfill_sub_2), .CK(WrClock), .CD(Reset), .Q(WCNT[2]))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_10 (.D(wfill_sub_3), .CK(WrClock), .CD(Reset), .Q(WCNT[3]))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_9 (.D(wfill_sub_4), .CK(WrClock), .CD(Reset), .Q(WCNT[4]))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_8 (.D(wfill_sub_5), .CK(WrClock), .CD(Reset), .Q(WCNT[5]))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_7 (.D(rfill_sub_0), .CK(RdClock), .CD(rRst), .Q(RCNT[0]))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_6 (.D(rfill_sub_1), .CK(RdClock), .CD(rRst), .Q(RCNT[1]))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_5 (.D(rfill_sub_2), .CK(RdClock), .CD(rRst), .Q(RCNT[2]))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_4 (.D(rfill_sub_3), .CK(RdClock), .CD(rRst), .Q(RCNT[3]))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_3 (.D(rfill_sub_4), .CK(RdClock), .CD(rRst), .Q(RCNT[4]))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_2 (.D(rfill_sub_5), .CK(RdClock), .CD(rRst), .Q(RCNT[5]))
             /* synthesis GSR="ENABLED" */;

    FD1S3BX FF_1 (.D(empty_d), .CK(RdClock), .PD(rRst), .Q(empty_i))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_0 (.D(full_d), .CK(WrClock), .CD(Reset), .Q(full_i))
             /* synthesis GSR="ENABLED" */;

    defparam w_gctr_cia.INJECT1_1 = "NO" ;
    defparam w_gctr_cia.INJECT1_0 = "NO" ;
    defparam w_gctr_cia.INIT1 =  16'h66AA ;
    defparam w_gctr_cia.INIT0 =  16'h66AA ;
    CCU2C w_gctr_cia (.A0(scuba_vlo), .A1(scuba_vhi), .B0(scuba_vlo), .B1(scuba_vhi), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(), .S0(), .S1(), .COUT(w_gctr_ci));

    defparam w_gctr_0.INJECT1_1 = "NO" ;
    defparam w_gctr_0.INJECT1_0 = "NO" ;
    defparam w_gctr_0.INIT1 =  16'h66AA ;
    defparam w_gctr_0.INIT0 =  16'h66AA ;
    CCU2C w_gctr_0 (.A0(wcount_0), .A1(wcount_1), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(w_gctr_ci), .S0(iwcount_0), .S1(iwcount_1), .COUT(co0));

    defparam w_gctr_1.INJECT1_1 = "NO" ;
    defparam w_gctr_1.INJECT1_0 = "NO" ;
    defparam w_gctr_1.INIT1 =  16'h66AA ;
    defparam w_gctr_1.INIT0 =  16'h66AA ;
    CCU2C w_gctr_1 (.A0(wcount_2), .A1(wcount_3), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co0), .S0(iwcount_2), .S1(iwcount_3), .COUT(co1));

    defparam w_gctr_2.INJECT1_1 = "NO" ;
    defparam w_gctr_2.INJECT1_0 = "NO" ;
    defparam w_gctr_2.INIT1 =  16'h66AA ;
    defparam w_gctr_2.INIT0 =  16'h66AA ;
    CCU2C w_gctr_2 (.A0(wcount_4), .A1(wcount_5), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co1), .S0(iwcount_4), .S1(iwcount_5), .COUT(co2));

    defparam r_gctr_cia.INJECT1_1 = "NO" ;
    defparam r_gctr_cia.INJECT1_0 = "NO" ;
    defparam r_gctr_cia.INIT1 =  16'h66AA ;
    defparam r_gctr_cia.INIT0 =  16'h66AA ;
    CCU2C r_gctr_cia (.A0(scuba_vlo), .A1(scuba_vhi), .B0(scuba_vlo), .B1(scuba_vhi), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(), .S0(), .S1(), .COUT(r_gctr_ci));

    defparam r_gctr_0.INJECT1_1 = "NO" ;
    defparam r_gctr_0.INJECT1_0 = "NO" ;
    defparam r_gctr_0.INIT1 =  16'h66AA ;
    defparam r_gctr_0.INIT0 =  16'h66AA ;
    CCU2C r_gctr_0 (.A0(rcount_0), .A1(rcount_1), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(r_gctr_ci), .S0(ircount_0), .S1(ircount_1), .COUT(co0_1));

    defparam r_gctr_1.INJECT1_1 = "NO" ;
    defparam r_gctr_1.INJECT1_0 = "NO" ;
    defparam r_gctr_1.INIT1 =  16'h66AA ;
    defparam r_gctr_1.INIT0 =  16'h66AA ;
    CCU2C r_gctr_1 (.A0(rcount_2), .A1(rcount_3), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co0_1), .S0(ircount_2), .S1(ircount_3), .COUT(co1_1));

    defparam r_gctr_2.INJECT1_1 = "NO" ;
    defparam r_gctr_2.INJECT1_0 = "NO" ;
    defparam r_gctr_2.INIT1 =  16'h66AA ;
    defparam r_gctr_2.INIT0 =  16'h66AA ;
    CCU2C r_gctr_2 (.A0(rcount_4), .A1(rcount_5), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co1_1), .S0(ircount_4), .S1(ircount_5), .COUT(co2_1));

    defparam precin_inst207.INJECT1_1 = "NO" ;
    defparam precin_inst207.INJECT1_0 = "NO" ;
    defparam precin_inst207.INIT1 =  16'h0000 ;
    defparam precin_inst207.INIT0 =  16'h0000 ;
    CCU2C precin_inst207 (.A0(scuba_vhi), .A1(scuba_vhi), .B0(scuba_vhi), 
        .B1(scuba_vhi), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(), .S0(), .S1(), .COUT(precin));

    defparam wfill_0.INJECT1_1 = "NO" ;
    defparam wfill_0.INJECT1_0 = "NO" ;
    defparam wfill_0.INIT1 =  16'h99AA ;
    defparam wfill_0.INIT0 =  16'h99AA ;
    CCU2C wfill_0 (.A0(scuba_vhi), .A1(wptr_0), .B0(scuba_vlo), .B1(rcount_w0), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(precin), .S0(), .S1(wfill_sub_0), .COUT(co0_2));

    defparam wfill_1.INJECT1_1 = "NO" ;
    defparam wfill_1.INJECT1_0 = "NO" ;
    defparam wfill_1.INIT1 =  16'h99AA ;
    defparam wfill_1.INIT0 =  16'h99AA ;
    CCU2C wfill_1 (.A0(wptr_1), .A1(wptr_2), .B0(rcount_w1), .B1(r_g2b_xor_cluster_0), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co0_2), .S0(wfill_sub_1), .S1(wfill_sub_2), .COUT(co1_2));

    defparam wfill_2.INJECT1_1 = "NO" ;
    defparam wfill_2.INJECT1_0 = "NO" ;
    defparam wfill_2.INIT1 =  16'h99AA ;
    defparam wfill_2.INIT0 =  16'h99AA ;
    CCU2C wfill_2 (.A0(wptr_3), .A1(wptr_4), .B0(rcount_w3), .B1(rcount_w4), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co1_2), .S0(wfill_sub_3), .S1(wfill_sub_4), .COUT(co2_2));

    defparam wfill_3.INJECT1_1 = "NO" ;
    defparam wfill_3.INJECT1_0 = "NO" ;
    defparam wfill_3.INIT1 =  16'h99AA ;
    defparam wfill_3.INIT0 =  16'h99AA ;
    CCU2C wfill_3 (.A0(wfill_sub_msb), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co2_2), .S0(wfill_sub_5), .S1(), .COUT());

    defparam precin_inst218.INJECT1_1 = "NO" ;
    defparam precin_inst218.INJECT1_0 = "NO" ;
    defparam precin_inst218.INIT1 =  16'h0000 ;
    defparam precin_inst218.INIT0 =  16'h0000 ;
    CCU2C precin_inst218 (.A0(scuba_vhi), .A1(scuba_vhi), .B0(scuba_vhi), 
        .B1(scuba_vhi), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(), .S0(), .S1(), .COUT(precin_1));

    defparam rfill_0.INJECT1_1 = "NO" ;
    defparam rfill_0.INJECT1_0 = "NO" ;
    defparam rfill_0.INIT1 =  16'h99AA ;
    defparam rfill_0.INIT0 =  16'h99AA ;
    CCU2C rfill_0 (.A0(scuba_vhi), .A1(wcount_r0), .B0(scuba_vlo), .B1(rptr_0), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(precin_1), .S0(), .S1(rfill_sub_0), .COUT(co0_3));

    defparam rfill_1.INJECT1_1 = "NO" ;
    defparam rfill_1.INJECT1_0 = "NO" ;
    defparam rfill_1.INIT1 =  16'h99AA ;
    defparam rfill_1.INIT0 =  16'h99AA ;
    CCU2C rfill_1 (.A0(wcount_r1), .A1(w_g2b_xor_cluster_0), .B0(rptr_1), 
        .B1(rptr_2), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co0_3), .S0(rfill_sub_1), .S1(rfill_sub_2), .COUT(co1_3));

    defparam rfill_2.INJECT1_1 = "NO" ;
    defparam rfill_2.INJECT1_0 = "NO" ;
    defparam rfill_2.INIT1 =  16'h99AA ;
    defparam rfill_2.INIT0 =  16'h99AA ;
    CCU2C rfill_2 (.A0(wcount_r3), .A1(wcount_r4), .B0(rptr_3), .B1(rptr_4), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co1_3), .S0(rfill_sub_3), .S1(rfill_sub_4), .COUT(co2_3));

    defparam rfill_3.INJECT1_1 = "NO" ;
    defparam rfill_3.INJECT1_0 = "NO" ;
    defparam rfill_3.INIT1 =  16'h99AA ;
    defparam rfill_3.INIT0 =  16'h99AA ;
    CCU2C rfill_3 (.A0(rfill_sub_msb), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co2_3), .S0(rfill_sub_5), .S1(), .COUT());

    defparam empty_cmp_ci_a.INJECT1_1 = "NO" ;
    defparam empty_cmp_ci_a.INJECT1_0 = "NO" ;
    defparam empty_cmp_ci_a.INIT1 =  16'h66AA ;
    defparam empty_cmp_ci_a.INIT0 =  16'h66AA ;
    CCU2C empty_cmp_ci_a (.A0(scuba_vlo), .A1(rden_i), .B0(scuba_vlo), .B1(rden_i), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(), .S0(), .S1(), .COUT(cmp_ci));

    defparam empty_cmp_0.INJECT1_1 = "NO" ;
    defparam empty_cmp_0.INJECT1_0 = "NO" ;
    defparam empty_cmp_0.INIT1 =  16'h99AA ;
    defparam empty_cmp_0.INIT0 =  16'h99AA ;
    CCU2C empty_cmp_0 (.A0(rcount_0), .A1(rcount_1), .B0(wcount_r0), .B1(wcount_r1), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(cmp_ci), .S0(), .S1(), .COUT(co0_4));

    defparam empty_cmp_1.INJECT1_1 = "NO" ;
    defparam empty_cmp_1.INJECT1_0 = "NO" ;
    defparam empty_cmp_1.INIT1 =  16'h99AA ;
    defparam empty_cmp_1.INIT0 =  16'h99AA ;
    CCU2C empty_cmp_1 (.A0(rcount_2), .A1(rcount_3), .B0(w_g2b_xor_cluster_0), 
        .B1(wcount_r3), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co0_4), .S0(), .S1(), .COUT(co1_4));

    defparam empty_cmp_2.INJECT1_1 = "NO" ;
    defparam empty_cmp_2.INJECT1_0 = "NO" ;
    defparam empty_cmp_2.INIT1 =  16'h99AA ;
    defparam empty_cmp_2.INIT0 =  16'h99AA ;
    CCU2C empty_cmp_2 (.A0(rcount_4), .A1(empty_cmp_set), .B0(wcount_r4), 
        .B1(empty_cmp_clr), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co1_4), .S0(), .S1(), .COUT(empty_d_c));

    defparam a0.INJECT1_1 = "NO" ;
    defparam a0.INJECT1_0 = "NO" ;
    defparam a0.INIT1 =  16'h66AA ;
    defparam a0.INIT0 =  16'h66AA ;
    CCU2C a0 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(empty_d_c), .S0(empty_d), .S1(), .COUT());

    defparam full_cmp_ci_a.INJECT1_1 = "NO" ;
    defparam full_cmp_ci_a.INJECT1_0 = "NO" ;
    defparam full_cmp_ci_a.INIT1 =  16'h66AA ;
    defparam full_cmp_ci_a.INIT0 =  16'h66AA ;
    CCU2C full_cmp_ci_a (.A0(scuba_vlo), .A1(wren_i), .B0(scuba_vlo), .B1(wren_i), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(), .S0(), .S1(), .COUT(cmp_ci_1));

    defparam full_cmp_0.INJECT1_1 = "NO" ;
    defparam full_cmp_0.INJECT1_0 = "NO" ;
    defparam full_cmp_0.INIT1 =  16'h99AA ;
    defparam full_cmp_0.INIT0 =  16'h99AA ;
    CCU2C full_cmp_0 (.A0(wcount_0), .A1(wcount_1), .B0(rcount_w0), .B1(rcount_w1), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(cmp_ci_1), .S0(), .S1(), .COUT(co0_5));

    defparam full_cmp_1.INJECT1_1 = "NO" ;
    defparam full_cmp_1.INJECT1_0 = "NO" ;
    defparam full_cmp_1.INIT1 =  16'h99AA ;
    defparam full_cmp_1.INIT0 =  16'h99AA ;
    CCU2C full_cmp_1 (.A0(wcount_2), .A1(wcount_3), .B0(r_g2b_xor_cluster_0), 
        .B1(rcount_w3), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co0_5), .S0(), .S1(), .COUT(co1_5));

    defparam full_cmp_2.INJECT1_1 = "NO" ;
    defparam full_cmp_2.INJECT1_0 = "NO" ;
    defparam full_cmp_2.INIT1 =  16'h99AA ;
    defparam full_cmp_2.INIT0 =  16'h99AA ;
    CCU2C full_cmp_2 (.A0(wcount_4), .A1(full_cmp_set), .B0(rcount_w4), 
        .B1(full_cmp_clr), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co1_5), .S0(), .S1(), .COUT(full_d_c));

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    defparam a1.INJECT1_1 = "NO" ;
    defparam a1.INJECT1_0 = "NO" ;
    defparam a1.INIT1 =  16'h66AA ;
    defparam a1.INIT0 =  16'h66AA ;
    CCU2C a1 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(full_d_c), .S0(full_d), .S1(), .COUT());

    assign Empty = empty_i;
    assign Full = full_i;


    // exemplar begin
    // exemplar attribute pdp_ram_0_0_1 MEM_LPC_FILE dphy_raw_fifo.lpc
    // exemplar attribute pdp_ram_0_0_1 MEM_INIT_FILE 
    // exemplar attribute pdp_ram_0_1_0 MEM_LPC_FILE dphy_raw_fifo.lpc
    // exemplar attribute pdp_ram_0_1_0 MEM_INIT_FILE 
    // exemplar attribute FF_73 GSR ENABLED
    // exemplar attribute FF_72 GSR ENABLED
    // exemplar attribute FF_71 GSR ENABLED
    // exemplar attribute FF_70 GSR ENABLED
    // exemplar attribute FF_69 GSR ENABLED
    // exemplar attribute FF_68 GSR ENABLED
    // exemplar attribute FF_67 GSR ENABLED
    // exemplar attribute FF_66 GSR ENABLED
    // exemplar attribute FF_65 GSR ENABLED
    // exemplar attribute FF_64 GSR ENABLED
    // exemplar attribute FF_63 GSR ENABLED
    // exemplar attribute FF_62 GSR ENABLED
    // exemplar attribute FF_61 GSR ENABLED
    // exemplar attribute FF_60 GSR ENABLED
    // exemplar attribute FF_59 GSR ENABLED
    // exemplar attribute FF_58 GSR ENABLED
    // exemplar attribute FF_57 GSR ENABLED
    // exemplar attribute FF_56 GSR ENABLED
    // exemplar attribute FF_55 GSR ENABLED
    // exemplar attribute FF_54 GSR ENABLED
    // exemplar attribute FF_53 GSR ENABLED
    // exemplar attribute FF_52 GSR ENABLED
    // exemplar attribute FF_51 GSR ENABLED
    // exemplar attribute FF_50 GSR ENABLED
    // exemplar attribute FF_49 GSR ENABLED
    // exemplar attribute FF_48 GSR ENABLED
    // exemplar attribute FF_47 GSR ENABLED
    // exemplar attribute FF_46 GSR ENABLED
    // exemplar attribute FF_45 GSR ENABLED
    // exemplar attribute FF_44 GSR ENABLED
    // exemplar attribute FF_43 GSR ENABLED
    // exemplar attribute FF_42 GSR ENABLED
    // exemplar attribute FF_41 GSR ENABLED
    // exemplar attribute FF_40 GSR ENABLED
    // exemplar attribute FF_39 GSR ENABLED
    // exemplar attribute FF_38 GSR ENABLED
    // exemplar attribute FF_37 GSR ENABLED
    // exemplar attribute FF_36 GSR ENABLED
    // exemplar attribute FF_35 GSR ENABLED
    // exemplar attribute FF_34 GSR ENABLED
    // exemplar attribute FF_33 GSR ENABLED
    // exemplar attribute FF_32 GSR ENABLED
    // exemplar attribute FF_31 GSR ENABLED
    // exemplar attribute FF_30 GSR ENABLED
    // exemplar attribute FF_29 GSR ENABLED
    // exemplar attribute FF_28 GSR ENABLED
    // exemplar attribute FF_27 GSR ENABLED
    // exemplar attribute FF_26 GSR ENABLED
    // exemplar attribute FF_25 GSR ENABLED
    // exemplar attribute FF_24 GSR ENABLED
    // exemplar attribute FF_23 GSR ENABLED
    // exemplar attribute FF_22 GSR ENABLED
    // exemplar attribute FF_21 GSR ENABLED
    // exemplar attribute FF_20 GSR ENABLED
    // exemplar attribute FF_19 GSR ENABLED
    // exemplar attribute FF_18 GSR ENABLED
    // exemplar attribute FF_17 GSR ENABLED
    // exemplar attribute FF_16 GSR ENABLED
    // exemplar attribute FF_15 GSR ENABLED
    // exemplar attribute FF_14 GSR ENABLED
    // exemplar attribute FF_13 GSR ENABLED
    // exemplar attribute FF_12 GSR ENABLED
    // exemplar attribute FF_11 GSR ENABLED
    // exemplar attribute FF_10 GSR ENABLED
    // exemplar attribute FF_9 GSR ENABLED
    // exemplar attribute FF_8 GSR ENABLED
    // exemplar attribute FF_7 GSR ENABLED
    // exemplar attribute FF_6 GSR ENABLED
    // exemplar attribute FF_5 GSR ENABLED
    // exemplar attribute FF_4 GSR ENABLED
    // exemplar attribute FF_3 GSR ENABLED
    // exemplar attribute FF_2 GSR ENABLED
    // exemplar attribute FF_1 GSR ENABLED
    // exemplar attribute FF_0 GSR ENABLED
    // exemplar end

endmodule
