[ActiveSupport PAR]
; Global primary clocks
GLOBAL_PRIMARY_USED = 3;
; Global primary clock #0
GLOBAL_PRIMARY_0_SIGNALNAME = sys_clk_c;
GLOBAL_PRIMARY_0_DRIVERTYPE = PLL;
GLOBAL_PRIMARY_0_LOADNUM = 337;
; Global primary clock #1
GLOBAL_PRIMARY_1_SIGNALNAME = rxhsbyteclk;
GLOBAL_PRIMARY_1_DRIVERTYPE = MIPIDPHY;
GLOBAL_PRIMARY_1_LOADNUM = 18;
; Global primary clock #2
GLOBAL_PRIMARY_2_SIGNALNAME = jtck[0];
GLOBAL_PRIMARY_2_DRIVERTYPE = CLK_PIN;
GLOBAL_PRIMARY_2_LOADNUM = 263;
; # of global secondary clocks
GLOBAL_SECONDARY_USED = 0;
; I/O Bank 0 Usage
BANK_0_USED = 3;
BANK_0_AVAIL = 7;
BANK_0_VCCIO = 2.5V;
BANK_0_VREF1 = NA;
BANK_0_VREF2 = NA;
; I/O Bank 1 Usage
BANK_1_USED = 14;
BANK_1_AVAIL = 14;
BANK_1_VCCIO = 2.5V;
BANK_1_VREF1 = NA;
BANK_1_VREF2 = NA;
; I/O Bank 2 Usage
BANK_2_USED = 10;
BANK_2_AVAIL = 16;
BANK_2_VCCIO = 2.5V;
BANK_2_VREF1 = NA;
BANK_2_VREF2 = NA;
