/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.14.0.75.2 */
/* Module Version: 5.8 */
/* Sun Jul 20 20:55:20 2025 */

/* parameterized module instance */
ddr_output __ (.clkout( ), .refclk( ), .reset( ), .data( ), .dout( ));
