/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 5.8 */
/* Mon Jul 14 12:14:24 2025 */

/* parameterized module instance */
ddr_output __ (.clkout( ), .refclk( ), .reset( ), .data( ), .dout( ));
