/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 5.7 */
/* Mon Jul 14 11:31:01 2025 */

/* parameterized module instance */
pll_sys_clk __ (.CLKI( ), .CLKOP( ), .CLKOS( ));
